Fix even more warnings
rswgnu/hyperbole pull request #100
Opened 2021-06-18 22:42 UTC by matsl

## What

Fix even more warnings. 

Tried to remove some more warnings but did also find some other problems. So contains also some replacements of functions that are deprecated but should be available from Emacs 27 (Only verified by by inspection.) and fixing a call with too few arguments.

## Why

We need to silence the output when compiling.

2021-06-20 13:10 UTC, rswgnu requested changes

2021-06-20 13:10 UTC, rswgnu commented on hui-mouse.el
> +	(t (diary-view-entries))))
Does this do the same thing as the mark function?  If not, need to update the doc string and manual entries.

2021-06-20 20:48 UTC, matsl commented on hsys-org.el
> -      (cond ((fboundp #'org-link-open-from-string)
In my dockerized Emacs 27.1 the help message says:

```org-open-link-from-string is an alias for org-link-open-from-string.

(org-open-link-from-string S &optional ARG)

  This function is obsolete since Org 9.3;
  use `org-link-open-from-string' instead.

Open a link in the string S, as if it was in Org mode.
Optional argument is passed to `org-open-file' when S is
a "file" link.

[back]
```
So I feel we can be safe not to check for that.

2021-06-20 21:00 UTC, matsl commented on hui-mouse.el
> +	(t (diary-view-entries))))
Thanks. Nice catch. Shall be `diary-mark-entries`. Fix is coming.

2021-06-21 12:35 UTC, rswgnu commented on hui-mouse.el
> +	(t (diary-view-entries))))
Sounds good for both your comments.

2021-06-21 12:36 UTC, rswgnu approved these changes

2021-06-21 20:03 UTC, merged