Add location checks to existing test cases
rswgnu/hyperbole pull request #158
Opened 2022-01-29 20:50 UTC by matsl

## What

Add location checks to existing test cases

## Why

More test are good.

## Note

Refactor the test cases by using a helper function to verify the button attributes. This is local for each test now but could be moved into a general helper maybe.

2022-01-29 22:22 UTC, rswgnu requested changes

2022-01-29 22:22 UTC, rswgnu commented on test/hbut-tests.el
> +  (should (eq (hattr:get (hbut:at-p) 'actype) actype))
You should cache the hbut:at-p result and reuse it throughout the attr tests.

2022-01-29 22:22 UTC, rswgnu commented on test/hui-tests.el
> +  (should (eq (hattr:get (hbut:at-p) 'actype) actype))
Same as prev commnt.

2022-02-03 22:41 UTC, matsl commented on test/hui-tests.el
> +  (should (eq (hattr:get (hbut:at-p) 'actype) actype))
Helper merged into one function using keyworded arguments as we talked about.

2022-02-03 22:41 UTC, matsl commented
PR is updated. PTAL.

2022-02-06 18:20 UTC, rswgnu approved these changes

2022-02-06 18:24 UTC, merged