Remove bad test case
rswgnu/hyperbole pull request #159
Opened 2022-01-29 21:08 UTC by matsl

## What

Remove bad designed test case

## Why

Was experimenting with ways to capture if something goes wrong when running the shell command by simulating that by calling `error` which for some reason does not work.  ert run fails even if the function under test tries to catch all errors!? Forgot though to leave that out when I made the previous PR. Sorry about that. This PR removes that test case and makes the unit test works. 

The original problem how to deal with user not having git in the path is not solved in the function under test.  Not sure how to do that and not sure if it is needed if user has cloned repo in the first place!?

## Note

The function under test could be a bad idea but the best I have come up with so far in trying to figure out what installation the user is running.

2022-01-29 22:30 UTC, rswgnu requested changes

2022-01-29 22:30 UTC, rswgnu commented on test/hypb-tests.el
> +      (mock (shell-command-to-string "git rev-parse HEAD") => "abcdefg")
Does this work if installed from elpa or with straight?  Can you test it against all installation methods aside fromthe tar all?

2022-02-03 20:20 UTC, matsl commented on test/hypb-tests.el
> +      (mock (shell-command-to-string "git rev-parse HEAD") => "abcdefg")
This is a unit test for the function that returns version info for a not official release such as an install from a git repo or from elpa-devel.

2022-02-03 20:21 UTC, matsl commented
Function is updates and test case changed to verify that. PTAL

2022-02-04 03:06 UTC, rswgnu approved these changes

2022-02-04 18:30 UTC, merged