Suggestion for some changes
rswgnu/hyperbole pull request #181
Opened 2022-03-31 20:58 UTC by matsl

## What

Suggestion for some changes.

## Why

Walked through the `FAST-DEMO` and found some things that might improve it.

## Note

See further comments below.

2022-03-31 21:02 UTC, matsl commented on FAST-DEMO
> +    {M-x dired-other-window RET ${hyperb:dir}/*.el RET}
There is no org-files in the root folder of Hyperbole so this command breaks.

- Suggested change to use the emacs lisp files instead but for fewer files we could use `.md` or `.otl`

2022-03-31 21:15 UTC, matsl commented on FAST-DEMO
> +    {C-x C-b C-x C-q M-x keep-lines RET .el$ RET C-x C-q}
Same here. What do you think of using Emacs Lisp files instead of Python and that we see to that those have been loaded into Emacs? I think following the `DEMO` does see to that.

2022-03-31 21:17 UTC, matsl commented on FAST-DEMO
> +    The shell command part of the demo requires as shell that is
Maybe overkill but I use `fish` and then the `shell` part breaks. So either something according to the lines here or just a comment?

2022-04-01 01:41 UTC, rswgnu requested changes

2022-04-01 01:41 UTC, rswgnu commented on FAST-DEMO
> +    The shell command part of the demo requires as shell that is
'a' shell not 'as'

2022-04-01 01:41 UTC, rswgnu commented on FAST-DEMO
> +       the demo.
Proofread and fix language here.

2022-04-01 06:58 UTC, matsl commented on FAST-DEMO
> +       the demo.
New version committed. PTAL.

2022-04-16 19:43 UTC, rswgnu commented on FAST-DEMO
> +    The shell command part of the demo requires as shell that is
Yes.

2022-04-17 14:49 UTC, rswgnu commented on FAST-DEMO
> +    {M-x dired-other-window RET ${hyperb:dir}/*.el RET}
This change is fine.

2022-04-17 14:50 UTC, rswgnu commented on FAST-DEMO
> +       the demo.
Fine, just update the PR.

2022-04-17 14:51 UTC, rswgnu commented on FAST-DEMO
> +    {C-u 0 C-c @ emacs-lisp-mode RET 33 RET}
Fine.

2022-04-17 14:52 UTC, rswgnu approved these changes

2022-04-17 14:52 UTC, merged