Make release updates
rswgnu/hyperbole pull request #189
Opened 2022-04-18 21:59 UTC by matsl

## What

Make release updates

## Why

Maybe something like this could be used. I have not included generation of the webpage yet. Not fully tested either since I don't want to start tagging the release and do ftp uploads and mocking these steps will still not fully verify things will work.

What do you think of trying out this together and see where things break? We can then see what makes sense to add to the process and what is best to have as separate steps?

2022-04-18 22:25 UTC, rswgnu commented
Sure, sounds good.  -- Bob

2022-04-18 22:29 UTC, rswgnu requested changes

2022-04-18 22:29 UTC, rswgnu commented on Makefile
> -# Once the release version number is updated in hyperbole.el and the release is pushed to
Please leave these comments somewhere in the Makefile so we know that Elpa builds are automatic.

2022-04-19 01:06 UTC, rswgnu requested changes

2022-04-19 01:06 UTC, rswgnu commented on Makefile
> +	echo "If this step failes check your work directory for not commited changes"
Replace with 'fails' and 'committed'.

2022-04-19 20:46 UTC, matsl commented on Makefile
> -# Once the release version number is updated in hyperbole.el and the release is pushed to
Added it at the top of the Makefile. Is that OK ro do you want it closer to the pkg and release targets?

2022-04-23 18:05 UTC, rswgnu commented on Makefile
> -# Once the release version number is updated in hyperbole.el and the release is pushed to
Is ok.

2022-04-23 18:06 UTC, rswgnu approved these changes

2022-04-23 21:08 UTC, merged