Example of doc changes to be within 80 char limit
rswgnu/hyperbole pull request #203
Opened 2022-07-09 08:52 UTC by matsl

## What 

Example of doc changes to be within 80 char limit.

## Why

Looking at how it would be to go down the route to fix the 80 char limit. You suggested that I would do a couple of docs to see what it means. I did slightly more but before doing all I would want to share it for feedback. It is really a lot to do but it triggers some good discussion points, see below.

Some things I noticed while doing this work:
* elisp mode defaults to fill column of 65 chars which is a bit surprising. We should probably have a style guide so that our doc strings look similar. Tried to look for a general style guide for Emacs about that but did not find it but maybe there is. I have for this work kept the default when formatting the comment body. I have tried to do that in as few cases as possible as that creates a bigger diff.
* Some first line comments are really close to 80 chars so simple things like dropping a `the` or similar suffice to fix those.
* Some first line comments mentions Hyperbole, or other facts that should be clear for the context, and can be fixed by removing these.
* Some first line comments tries to capture everything about a function. Both the major functionality but also all alternatives. This might be the ones that would be hardest to change, but to be honest, I find them sometimes hard to read and understand. So forcing us to describe it within 80 chars would have the good side effect of making them more readable since long sentences are harder to read.
* Some functions have slightly misleading names. Example of that are the `-p` (predicate functions) where the comment line has to compensate for that by explain more what the function does. A good function name could make the task of the first comment line smaller and by that possible to capture in the less space.
* Functions with a lot of alternatives, controlled by optional arguments, might benefit from being split into multiple functions making each function both easier to test and to describe?
* Some techniques I have used:
   * Simply write a shorter first comment line and kept the original comment line in the comment body.
   * Cut the comment line in two. Moving the second part of it into the comment body.
   * Cut our part of the doc in the first line and then write a longer part describing the cut out piece in the comment body.
* My flycheck warned about single quotes in some doc strings so I fixed those as well. Not sure that is necessary. It just happened when I was at it. So feel free to ignore those changes.

2022-07-16 21:43 UTC, rswgnu commented
See comments above so far to integrate.  I have more to review.

2022-07-17 19:31 UTC, matsl commented
Hi @rswgnu, I can't see any comments I'm afraid. Could it be that you have started a review and that is it not completed yet? I normally don't use the review feature but write single comments so I'm not sure how the review thing works. I think you need to finish it before the comments becomes available to me! (or something like that. I really should learn how that can be used. Might be a good thing.)

2022-07-17 22:50 UTC, rswgnu commented
I think you are right.  I’ll figure out a solution and let’s move to the smaller chunks so I can approve them faster.

-- Bob

> On Jul 17, 2022, at 3:31 PM, Mats Lidell ***@***.***> wrote:
> 
> ﻿
> Hi @rswgnu, I can't see any comments I'm afraid. Could it be that you have started a review and that is it not completed yet? I normally don't use the review feature but write single comments so I'm not sure how the review thing works. I think you need to finish it before the comments becomes available to me! (or something like that. I really should learn how that can be used. Might be a good thing.)
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.

2022-07-18 19:17 UTC, matsl commented
@rswgnu So your suggestion is that we shall close this PR and that I should come back with smaller PRs?

2022-07-18 23:30 UTC, rswgnu requested changes
This has the comments I made with updates I made but just for the first several entries.  I do suggest you make these changes, close this PR, and then submit smaller, chunked ones that I can process each day for you.  Thanks, Bob

2022-07-20 17:58 UTC, closed without merging

2022-10-11 08:08 UTC, rswgnu commented
Yes, I just submitted my partial review with the updates to make before you
do the 'chunked' PRs.

Cheers,

Bob

On Mon, Jul 18, 2022 at 3:17 PM Mats Lidell ***@***.***>
wrote:

> @rswgnu <https://github.com/rswgnu> So your suggestion is that we shall
> close this PR and that I should come back with smaller PRs?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/rswgnu/hyperbole/pull/203#issuecomment-1188162160>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE5WPD5QSLQCXOM2RW4MG6TVUWUTRANCNFSM53DB3TMQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-11 08:21 UTC, rswgnu commented
Thanks.  Will look in detail at this letter but excited you have worked on
this.

Just FYI, Hyperbole SYMBOL-OR-NAME means not just an Elisp symbol or
symbol-name but one created in Hyperbole's own namespaces like actypes::
and ibtypes::, so this is not equivalent to saying just SYMBOL-OR-NAME.
Most of the other initial changes I looked at are fine.

Cheers,

Bob


On Sat, Jul 9, 2022 at 4:52 AM Mats Lidell ***@***.***> wrote:

> What
>
> Example of doc changes to be within 80 char limit.
> Why
>
> Looking at how it would be to go down the route to fix the 80 char limit.
> You suggested that I would do a couple of docs to see what it means. I did
> slightly more but before doing all I would want to share it for feedback.
> It is really a lot to do but it triggers some good discussion points, see
> below.
>
> Some things I noticed while doing this work:
>
>    - elisp mode defaults to fill column of 65 chars which is a bit
>    surprising. We should probably have a style guide so that our doc strings
>    look similar. Tried to look for a general style guide for Emacs about that
>    but did not find it but maybe there is. I have for this work kept the
>    default when formatting the comment body. I have tried to do that in as few
>    cases as possible as that creates a bigger diff.
>    - Some first line comments are really close to 80 chars so simple
>    things like dropping a the or similar suffice to fix those.
>    - Some first line comments mentions Hyperbole, or other facts that
>    should be clear for the context, and can be fixed by removing these.
>    - Some first line comments tries to capture everything about a
>    function. Both the major functionality but also all alternatives. This
>    might be the ones that would be hardest to change, but to be honest, I find
>    them sometimes hard to read and understand. So forcing us to describe it
>    within 80 chars would have the good side effect of making them more
>    readable since long sentences are harder to read.
>    - Some functions have slightly misleading names. Example of that are
>    the -p (predicate functions) where the comment line has to compensate
>    for that by explain more what the function does. A good function name could
>    make the task of the first comment line smaller and by that possible to
>    capture in the less space.
>    - Functions with a lot of alternatives, controlled by optional
>    arguments, might benefit from being split into multiple functions making
>    each function both easier to test and to describe?
>    - Some techniques I have used:
>       - Simply write a shorter first comment line and kept the original
>       comment line in the comment body.
>       - Cut the comment line in two. Moving the second part of it into
>       the comment body.
>       - Cut our part of the doc in the first line and then write a longer
>       part describing the cut out piece in the comment body.
>    - My flycheck warned about single quotes in some doc strings so I
>    fixed those as well. Not sure that is necessary. It just happened when I
>    was at it. So feel free to ignore those changes.
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/rswgnu/hyperbole/pull/203
> Commit Summary
>
>    - dae9073
>    <https://github.com/rswgnu/hyperbole/pull/203/commits/dae90737a568b965ea65e00a05421de588230743>
>    Example of doc changes to be within 80 char limit
>
> File Changes
>
> (22 files <https://github.com/rswgnu/hyperbole/pull/203/files>)
>
>    - *M* hact.el
>    <https://github.com/rswgnu/hyperbole/pull/203/files#diff-1b6353d249038bcdce557dbc8cc7762891e11cff2c1ea87401661e9ad8f7be4d>
>    (26)
>    - *M* hactypes.el
>    <https://github.com/rswgnu/hyperbole/pull/203/files#diff-94bfcb748e4d9925511e6dbeaf2ae1c8b57c002b01193db0b5960853c1cd7bc8>
>    (14)
>    - *M* hargs.el
>    <https://github.com/rswgnu/hyperbole/pull/203/files#diff-0d5db25e8f4cce2f5c3775f263991f45f95b8c7189f6458719803b5d30baa88d>
>    (10)
>    - *M* hbdata.el
>    <https://github.com/rswgnu/hyperbole/pull/203/files#diff-fec33d7d02d28deb8c27356d77fcc645e833158b5359134f505d1f566304e63c>
>    (22)
>    - *M* hbut.el
>    <https://github.com/rswgnu/hyperbole/pull/203/files#diff-d48e3b69335bb27cacda9fd461b760993521c24404acb8ed67b7b05bc7e612d3>
>    (170)
>    - *M* hhist.el
>    <https://github.com/rswgnu/hyperbole/pull/203/files#diff-58ac2632d7bc28a0431a44fa50c2157f23817549614481c12edb09086581d4b9>
>    (7)
>    - *M* hib-debbugs.el
>    <https://github.com/rswgnu/hyperbole/pull/203/files#diff-859cba9c83b5dd489155baaa7633a87b6ef27f081545724907e720393e1e5e4c>
>    (44)
>    - *M* hib-doc-id.el
>    <https://github.com/rswgnu/hyperbole/pull/203/files#diff-aa6c7103b1d777b08768e2fa1b789dec3d23ea67cbfb83011bb540812d675eb5>
>    (7)
>    - *M* hib-kbd.el
>    <https://github.com/rswgnu/hyperbole/pull/203/files#diff-5c8a26d7fd9b70b63f8653cb47bbb91551c5d6de30c736ac5964f2af69ebd2aa>
>    (52)
>    - *M* hmouse-tag.el
>    <https://github.com/rswgnu/hyperbole/pull/203/files#diff-214f349f95684f4ce9e2894de24538961478cafbd388e9997dee63d4a4889039>
>    (3)
>    - *M* kotl/kcell.el
>    <https://github.com/rswgnu/hyperbole/pull/203/files#diff-94019aab1f6c59b26697346e08b8a32cb322ecadd63172daa897bb3385045c47>
>    (9)
>    - *M* kotl/kexport.el
>    <https://github.com/rswgnu/hyperbole/pull/203/files#diff-20bdf3429289b5fe3829008fde8d24c0d0e7a0165e7f2f8b2074add08c56ef13>
>    (44)
>    - *M* kotl/kfile.el
>    <https://github.com/rswgnu/hyperbole/pull/203/files#diff-8faa930d9998a3e4ae2044cc0b42cd25c991d54b00ba6f9c60c1924a3c2e2481>
>    (17)
>    - *M* kotl/kfill.el
>    <https://github.com/rswgnu/hyperbole/pull/203/files#diff-5022d2dfa1c98ce3bb7428e5fd46bbd85c0e0b74bbd1e91219a91d736f8b1846>
>    (15)
>    - *M* kotl/kimport.el
>    <https://github.com/rswgnu/hyperbole/pull/203/files#diff-3af72a0be8ef3d4c6f22f91e630cbab15b3430cf9f97fa6a2568778ad1233ecd>
>    (27)
>    - *M* kotl/klabel.el
>    <https://github.com/rswgnu/hyperbole/pull/203/files#diff-9ff18afedca60f5b98fdec8cc494906a6e4ffea5411007cb96d2e76aa313cd75>
>    (27)
>    - *M* kotl/klink.el
>    <https://github.com/rswgnu/hyperbole/pull/203/files#diff-084e647db6d657f8446f12399b8aea1a55409915f84eb2467f5643b6bfd33235>
>    (16)
>    - *M* kotl/kotl-mode.el
>    <https://github.com/rswgnu/hyperbole/pull/203/files#diff-8661cda44144a58ce347529136069cf6f1385d92db7ba34e6f1d2db08f6cdb44>
>    (124)
>    - *M* kotl/kotl-orgtbl.el
>    <https://github.com/rswgnu/hyperbole/pull/203/files#diff-a0dff45482591fc0713bb2bcac65ee1c9899d1b2dbf2b4c74aa264203ee36ff1>
>    (4)
>    - *M* kotl/kproperty.el
>    <https://github.com/rswgnu/hyperbole/pull/203/files#diff-e4913ba5b0233485c01f8e2784277661f81ecb8f8ef253a74dbb9db33e6dac8d>
>    (12)
>    - *M* kotl/kview.el
>    <https://github.com/rswgnu/hyperbole/pull/203/files#diff-b753844a60c208f31b10afac6cba57a21d61ca060d0a50d0e99c604b2a3125e0>
>    (92)
>    - *M* kotl/kvspec.el
>    <https://github.com/rswgnu/hyperbole/pull/203/files#diff-68ff3ece493be04f95219a28b0c6b5cf3551aa7c044a5ab07cdc41af56774526>
>    (5)
>
> Patch Links:
>
>    - https://github.com/rswgnu/hyperbole/pull/203.patch
>    - https://github.com/rswgnu/hyperbole/pull/203.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/rswgnu/hyperbole/pull/203>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE5WPD4MPFHKPD7KT6ZDYSLVTE4WBANCNFSM53DB3TMQ>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>