Remove last mentioning xemacs
rswgnu/hyperbole pull request #204
Opened 2022-07-09 16:12 UTC by matsl

## What

Remove last mentioning xemacs.

## Why

Since XEmacs is not supported it is strange to have code and comments that mentions XEmacs.

## Note

This PR has two parts:

1. Remove XEmacs from a comment where it looks like the comment still is valid for Emacs so changed the sentence to work with  that.
2. Second is more controversial. From the existing comment is sounds like the preferred name was not chosen due to a XEmacs byte compile bug. So I got ambitious and renamed it back, removed the comment and added an obsolete definition. An alternative would to keep the function as is and simply remove the comment!? (Learned to use wgrep which was handy and could be useful for future changes like this.)

2022-07-16 21:33 UTC, rswgnu requested changes
See inline comment on version numbers.  Approved once you make that change.

2022-07-16 21:33 UTC, rswgnu commented on kotl/kotl-mode.el
> +(defalias 'kotl-mode:beginning-of-visual-line 'kotl-mode:beginning-of-line)
Would prefer version 8.0.1 when you make any versioned changes since these will be in that release.

2022-07-17 08:16 UTC, matsl commented on kotl/kotl-mode.el
> +(defalias 'kotl-mode:beginning-of-visual-line 'kotl-mode:beginning-of-line)
Yes. I misunderstood the `WHEN` parameter to be when the alias would be **removed** and thus effectively remove the old function. Looking now I understand it is when the it is **first** marked as obsolete so **8.0.1** make perfect sense. Thanks for pointing that out. I will fix.

2022-07-17 08:27 UTC, matsl commented on kotl/kotl-mode.el
> +(defalias 'kotl-mode:beginning-of-visual-line 'kotl-mode:beginning-of-line)
Noticed that I marked `hypb:replace-match-string` as obsolete from _9.0_ as well. So I fixed this with this PR too.

2022-07-17 14:30 UTC, merged