Doc strings within 80 char limit for hbut.el
rswgnu/hyperbole pull request #217
Opened 2022-07-20 21:48 UTC by matsl

## What

Doc strings within 80 char limit for hbut.el

## Why

Extracted from longer PR for easier review. It is still quite long. Let me know if I should split it further.

2022-07-21 05:41 UTC, rswgnu requested changes

2022-07-21 05:41 UTC, rswgnu commented on hbut.el
> +  "True within a programming language buffer and prior match is outside a comment."
"True if in a programming mode and regexp match is outside a comment, else nil."

2022-07-21 05:41 UTC, rswgnu commented on hbut.el
> +  "Rename an implicit button label in the current buffer from OLD-LBL to NEW-LBL.
"Change an implicit button name in the current buffer from OLD-LBL to NEW-LBL.

2022-07-21 05:41 UTC, rswgnu commented on hbut.el
> +  "Apply BUT-FUNC to the labeled implicit buttons.
"Apply BUT-FUNC to the visible, named implicit buttons.
If REGEXP-MATCH is non-nil, only buttons which match this argument
are considered.

2022-07-21 05:41 UTC, rswgnu commented on hbut.el
> +found, else nil."
"If point is on an implicit button, optional IBUT, move to the start of its name.
If name is found, leave point after its opening delimiter and set the name
and lbl-key properties of IBUT.  Return t if name is found, else nil."

2022-07-21 05:41 UTC, rswgnu commented on hbut.el
> +  "Move to the start of the nearest implicit buttons delimited button name.
"Move to the name of the nearest named implicit button matching LBL-KEY.

2022-07-21 05:41 UTC, rswgnu commented on hbut.el
> +  "Move to within nearest implicit button text.
"Move to the text of the nearest implicit button matching LBL-KEY.

2022-07-21 05:41 UTC, rswgnu commented on hbut.el
> +  "String inserted immediately after a newly created implicit button label.
"String inserted immediately after a newly created implicit button name.

2022-07-21 05:41 UTC, rswgnu commented on hbut.el
> +  "Regular expression that separates an implicit button label from its button text.")
"Regular expression that separates an implicit button name from its button text.")

2022-07-21 05:41 UTC, rswgnu commented on hbut.el
> +  "Activate an implicit link REFERENT, either a key series, a URL or a path."
"Activate an implicit link REFERENT, either a key series, a url or a path."

2022-07-21 05:41 UTC, rswgnu commented on hbut.el
> +buttons perform a grep-like function over a current repositorys git
Here is a sample use case.  Create a button type whose buttons
perform a grep-like function over a current repository's git

2022-07-21 08:07 UTC, matsl commented on hbut.el
> +  "Activate an implicit link REFERENT, either a key series, a URL or a path."
This is the same text as given. Did you forget to do the change you wanted?

2022-07-27 23:40 UTC, rswgnu approved these changes

2022-08-01 12:05 UTC, merged