Doc strings within 80 char limit for hib-kbd.el
rswgnu/hyperbole pull request #220
Opened 2022-07-20 21:58 UTC by matsl

## What

Doc strings within 80 char limit for hib-kbd.el

## Why

Extracted from longer PR for easier review.

2022-07-21 03:31 UTC, rswgnu requested changes

2022-07-21 03:31 UTC, rswgnu commented on hib-kbd.el
> +Return iff it starts and ends with these delimiters."
Return nil is STR does not start and end with the given delimiters."

2022-07-21 03:31 UTC, rswgnu commented on hib-kbd.el
> +A command of the form M-x command."
That is, 'M-x command'.

2022-07-21 03:31 UTC, rswgnu commented on hib-kbd.el
> +  "True if normalized, non-nil KEY-SERIES is given when in a HyControl mode.
"Return t if KEY-SERIES is normalized, non-nil and in HyControl mode, else nil.
Allow for multiple key sequences strung together."

2022-07-21 09:44 UTC, matsl commented on hib-kbd.el
> +A command of the form M-x command."
FYI: checkdocs complains: ```Keycode` M-x embedded in doc string.  Use \\<mapvar> & \\[command] instead```
Not sure how to apply that so keeping the suggested text for now. Will not cause a warning when byte compiling.

2022-07-27 23:44 UTC, rswgnu approved these changes

2022-08-01 12:14 UTC, merged