Doc strings within 80 char limit for klabel.el
rswgnu/hyperbole pull request #228
Opened 2022-07-21 14:17 UTC by matsl

## What

Doc strings within 80 char limit for klabel.el.

## Why

Extracted from longer PR for easier review.

2022-07-25 22:02 UTC, rswgnu requested changes

2022-07-25 22:02 UTC, rswgnu commented on kotl/klabel.el
> +  "Update the labels of current cell, its siblings and their subtrees if need be.
```suggestion
  "Update the labels of current cell, its following siblings and their subtrees.
```

2022-07-25 22:02 UTC, rswgnu commented on kotl/klabel.el
> +The label type may be different.  Return NEW-LABEL string."
```suggestion
The new label type may differ from the old type.
Return NEW-LABEL string."
```

2022-07-27 23:46 UTC, rswgnu approved these changes

2022-08-01 12:25 UTC, matsl commented on ChangeLog
> +* kotl/kcell.el: Shorten docs strings to be within 80 char limit
```suggestion
* kotl/kcell.el: Shorten docs strings to be within 80 char limit.
```

2022-08-01 12:27 UTC, matsl commented on ChangeLog
> +* kotl/kcell.el: Shorten docs strings to be within 80 char limit
keyboard slip? Revert this change.

2022-08-01 12:30 UTC, merged