Doc strings within 80 char limit for kview.el
rswgnu/hyperbole pull request #233
Opened 2022-07-21 14:32 UTC by matsl

## What

Doc strings within 80 char limit for kview.el.

## Why

Extracted from longer PR for easier review.

2022-10-05 05:13 UTC, rswgnu requested changes

2022-10-05 18:21 UTC, matsl commented on kotl/kview.el
> +  "*Default label-type to use for new koutlines.  Default value is `alpha'.
I can revert this. The quotes is not a `docstring` length issue so probably something `flycheck` reported and I tried to fix. We can defer that to later since I think there are more warnings of this problem and we should fix them in the same way.

2022-10-06 22:26 UTC, rswgnu requested changes

2022-10-06 22:26 UTC, rswgnu commented on kotl/kview.el
> +end point of the cell contents.
```suggestion
  "Return the first point that is followed by an invisible character.
Start from point or optional POS.  If none are found, return the
end point of the cell contents.
```

2022-10-06 22:26 UTC, rswgnu commented on kotl/kview.el
> +used.
```suggestion
Optional ID-COUNTER is the maximum permanent id previously utilized in this outline.
Optional LABEL-TYPE, LEVEL-INDENT, LABEL-SEPARATOR, LABEL-MIN-WIDTH,
BLANK-LINES, LEVELS-TO-SHOW, and LINES-TO-SHOW may also be given;
otherwise, default values are used.
```

2022-10-06 22:26 UTC, rswgnu commented on kotl/kview.el
> +end point of the cell contents.
```suggestion
  "Return the first point that is followed by an invisible character.
Start from point or optional POS.  If not found, return the
endpoint of the cell contents.
```

2022-10-06 22:26 UTC, rswgnu commented on kotl/kview.el
> +Start from point or optional POS.  If none are found return (point-max)."
```suggestion
  "Return the first point that is followed by a visible character.
Start from point or optional POS.  If not found, return (point-max)."
```

2022-10-06 22:26 UTC, rswgnu commented on kotl/kview.el
> +On success return t, else nil."
```suggestion
  "Move point to start of cell with permanent IDSTAMP-OR-STRING.
On success, return t, else nil."
```

2022-10-06 22:26 UTC, rswgnu commented on kotl/kview.el
> +Start from point or optional POS.  If none are found return (point-min).
```suggestion
  "Return the first preceding point that is followed by a visible character.
Start from point or optional POS.  If not found, return (point-min).
```

2022-10-09 14:00 UTC, rswgnu requested changes

2022-10-09 17:06 UTC, rswgnu approved these changes

2022-10-09 17:36 UTC, merged