Do not use obsolete functions
rswgnu/hyperbole pull request #236
Opened 2022-07-24 21:27 UTC by matsl

## What

Do not use obsolete functions.

## Why

We can use the new function directly since they are supported from 27.2.

## Note

Also fixes a duplication related to an obsolete function. Maybe I missed this or made a bad rebase!?

2022-07-27 23:01 UTC, rswgnu requested changes

2022-07-27 23:01 UTC, rswgnu commented on hibtypes.el
> +           (setq label (replace-regexp-in-string "[^:]+::" "" label nil t))
Similarly, if you have removed all of these calls, remove hypb:...

2022-08-01 13:04 UTC, matsl commented on hibtypes.el
> +           (setq label (replace-regexp-in-string "[^:]+::" "" label nil t))
Almost same in this case: marked as obsolete here: https://github.com/rswgnu/hyperbole/blob/75c9214c359af9fd33960f43477ceea5e170686f/hypb.el#L573 but since argument order is different there is no replacement so if someone is using this they will need to figure out the difference. Marking it as obsolete and keeping the function for a a while remediates that. *BUT* if we view this as a purely internal function, no likely external usage, I guess we could just remove it?

WDYT?

2022-08-01 23:21 UTC, rswgnu commented on hact.el
> +	((byte-code-function-p action)
Yes, remove it.

2022-08-02 07:25 UTC, matsl commented on hypb.el
> -(make-obsolete 'hypb:replace-match-string 'replace-regexp-in-string "8.0.1")
Removal of hypb:replace-match-string.

2022-08-02 07:26 UTC, matsl commented on hypb.el
> -;;;###autoload
Removal of obsolete definition of hypb:emacs-byte-code-p

2022-08-02 07:27 UTC, matsl commented on hibtypes.el
> +           (setq label (replace-regexp-in-string "[^:]+::" "" label nil t))
OK. Removed it as well.

2022-09-19 20:39 UTC, matsl commented
@rswgnu I learned today how easy it is to remove a file from a PR and then it was easy to repurpose this PR to just a small cleanup. PTAL.

2022-09-25 20:50 UTC, rswgnu commented
Let's work on the merge of this when we are together as well.

2022-09-26 21:15 UTC, matsl commented
@rswgnu With the fix of the CI this PR now builds so can be merged if approved. Was that the reason for merging this together?

It has 9 commits but all boils down to two small changes. Replace of one function and removal of another. So just look at the combined result and not each commit. I'll squash so the commits becomes one.

2022-09-26 23:29 UTC, rswgnu approved these changes

2022-09-27 06:56 UTC, merged