Doc strings within 80 char limit for hmouse-tag.el
rswgnu/hyperbole pull request #247
Opened 2022-07-27 09:14 UTC by matsl

## What

Doc strings within 80 char limit for hmouse-tag.el.

## Why

Warnings, warnings, warnings...

2022-08-14 15:37 UTC, rswgnu requested changes

2022-08-14 15:37 UTC, rswgnu commented on hmouse-tag.el
> +  "Regexp matching the first character of a Lisp identifier.
```suggestion
  "Character set regexp matching the first character of a Lisp identifier.")
```

2022-08-14 15:37 UTC, rswgnu commented on hmouse-tag.el
> +The square brackets are included.")
```suggestion
```

2022-08-14 15:37 UTC, rswgnu commented on hmouse-tag.el
> +arg SHOW-DOC non-nil show its documentation.
```suggestion
arg SHOW-DOC non-nil, show its documentation.
```

2022-08-14 15:37 UTC, rswgnu commented on hmouse-tag.el
> +  "Non-nil if point is on the first line of a non-alias Lisp definition.
```suggestion
"Return t if in a non-help buf and on line 1 of a non-alias Lisp def, else nil."
```

2022-08-14 15:37 UTC, rswgnu commented on hmouse-tag.el
> +Returns nil if in a help buffer."
```suggestion
```

2022-08-14 15:37 UTC, rswgnu commented on hmouse-tag.el
> +    "Non-nil if point is on the first line of a Lisp library load expression."
```suggestion
"Return t if on the first line of a Lisp library load expression, else nil."
```

2022-08-14 15:37 UTC, rswgnu commented on hmouse-tag.el
> +  "When in change-log mode match to bound Elisp identifiers only.
```suggestion
  "When in change-log mode, match to bound Elisp identifiers only.
```

2022-08-14 15:37 UTC, rswgnu commented on hmouse-tag.el
> +Match to bound Elisp identifiers only and those with a '-'
```suggestion
Also match to identifiers with a '-' in the middle.
```

2022-08-14 15:37 UTC, rswgnu commented on hmouse-tag.el
> +somewhere in the middle.  These tight tests help eliminate
```suggestion
These tight tests help eliminate undesired matches.
```

2022-08-14 15:37 UTC, rswgnu commented on hmouse-tag.el
> +undesired matches.  Returns matching ELisp tag name that point is
```suggestion
Return matching Elisp tag name that point is within, else nil."
```

2022-08-14 15:37 UTC, rswgnu commented on hmouse-tag.el
> +within, else nil."
```suggestion
```

2022-08-14 15:37 UTC, rswgnu commented on hmouse-tag.el
> +  "If Jedi identifier server is running, test and use it to jump to the definition.
```suggestion
  "If Jedi Python identifier server is running, use it to jump to the definition.
```

2022-08-14 15:37 UTC, rswgnu commented on hmouse-tag.el
> +  "If within a Java @see comment display the associated definition for editing.
```suggestion
  "If within a Java @see comment, edit the def and return non-nil, else nil.
```

2022-08-14 17:29 UTC, matsl commented
@rswgnu Had to mix committing changes in the GUI with rebase and resolve some more complicated changes manually. 

When there are multi line changes I think it will be easier for me if all lines in the docstrings are changed within one suggested commit. I think that is possible by selecting multiple lines when creating the suggestion. Mark the fist line and use the mouse to drag to the last line you want to change.

2022-09-11 16:26 UTC, rswgnu requested changes

2022-09-11 16:26 UTC, rswgnu commented on hmouse-tag.el
> +  "Non-nil if point is on the first line of a non-alias Lisp definition."
```suggestion
  "Return non-nil if point is on the first line of a non-alias Lisp definition.
  Apply only to non-help buffers and return nil in others."
```

2022-09-11 16:26 UTC, rswgnu commented on hmouse-tag.el
> +Return TAG."
```suggestion
  "Try to flash TAG at START to END in current buffer and return TAG.
This indicates that TAG is serving as a hyperlink button."
```

2022-10-02 21:43 UTC, rswgnu requested changes

2022-10-02 21:43 UTC, rswgnu commented on hmouse-tag.el
> +known Emacs Lisp identifier."
```suggestion
  "Return non-nil if point is within a known Lisp identifier.
The Lisp identifier is either listed in a tags table or is a
known Emacs Lisp identifier."
```

2022-10-05 05:08 UTC, rswgnu approved these changes

2022-10-05 18:06 UTC, merged