First stab at register support
rswgnu/hyperbole pull request #272
Opened 2022-08-20 21:48 UTC by matsl

## What

First stab at register support

## Why

Sharing the first stab at implementing register support of buttons for ideas and comments.

2022-08-27 11:50 UTC, matsl commented
@rswgnu Added support for link-to-ibut

2022-09-11 16:28 UTC, matsl commented
@rswgnu Added test cases to the PR. The test `hypb-register-test--register-val-insert` fails due to what it seems a problem with `link-to-ibut`. The setup is in the test. I will try to debug it further but maybe you can have a look?

2022-09-11 19:56 UTC, rswgnu requested changes

2022-09-11 19:56 UTC, rswgnu commented on ChangeLog
> +* test/hypb-register-tests.el (hypb-register-test--create-register-content)
Everywhere you use hypb-register, let's change that to hui-register since this is part of the UI.

2022-09-11 19:56 UTC, rswgnu commented on hypb-register.el
> +    (when (null label)
```suggestion
    (unless label
```

2022-09-11 19:56 UTC, rswgnu commented on hypb-register.el
> +     :file (buffer-file-name)
Note that there are explicit and implicit buttons where the button source buffer does not have an attached file, so you'll need to handle those appropriately, i.e. links to them work only within the current Emacs session, which may be okay for use with registers which typically are not stored across sessions either.

2022-09-11 19:56 UTC, rswgnu commented on hypb-register.el
> +  (let ((buf (marker-buffer (hypb-register-but-mpos val)))
What if the source buffer of the button no longer exists?  You need to read it back in if it has a file attached.

2022-09-11 19:56 UTC, rswgnu commented on test/hypb-register-tests.el
> +          (should (equal (hypb-register-but-label content) "label"))
Use a label with spaces in it here to be sure it is converted into a lbl-key without spaces as necessary (internally).

2022-09-11 19:56 UTC, rswgnu commented on test/hypb-register-tests.el
> +          (register-val-jump-to content nil)
I think you should be testing the interactive register functions.  So 'insert-register' to test inserting, 'copy-to-register' to save a button to a register, 'jump-to-register' to go to it, and so forth.

2022-09-14 20:27 UTC, matsl commented on ChangeLog
> +* test/hypb-register-tests.el (hypb-register-test--create-register-content)
Changed name to hui-register

2022-09-14 20:29 UTC, matsl commented on test/hypb-register-tests.el
> +          (should (equal (hypb-register-but-label content) "label"))
Changed test to use label "label label"

2022-09-14 20:31 UTC, matsl commented on test/hypb-register-tests.el
> +          (register-val-jump-to content nil)
I can add that as well. The high level functions use the methods we test here so more proper unit tests IMHO.

2022-09-17 22:44 UTC, matsl commented on hypb-register.el
> +  (let ((buf (marker-buffer (hypb-register-but-mpos val)))
Added an error message if buffer does not exists. Same behavior as for other types register jump to.

2022-09-17 22:51 UTC, matsl commented on hypb-register.el
> +     :file (buffer-file-name)
Does not `link-to-ebut` require a file name? 

How should we support the case for origin buffer with no filename? Shall we jump to button source and execute the action key instead of using `link-to-ebut`?

2022-09-19 21:23 UTC, matsl commented on test/hypb-register-tests.el
> +          (register-val-jump-to content nil)
@rswgnu `copy-to-register` copies the region to a register so I don't know how I could use that in combination with this!? 
On the other hand I noticed we have the function `hui-copy-to-register` Maybe that could embrace this functionality and if on an ibut or ebut copy that instead of thing at point?  wdut?

2022-09-25 20:47 UTC, rswgnu commented on test/hypb-register-tests.el
> +          (register-val-jump-to content nil)
I think we'll need to do some work on this together.  We just need to decide on the format of the buttons to store, adjust the hui-copy-to-register code and then work out the insertion code, relativizing paths as needed.

2022-09-26 21:24 UTC, matsl commented on test/hypb-register-tests.el
> +          (register-val-jump-to content nil)
So you think `hui-copy-to-register` is the right function to wrap this behavior?

2022-10-02 08:51 UTC, matsl commented on test/hypb-register-tests.el
> +          (register-val-jump-to content nil)
@rswgnu Added a proof of concept letting the `hui-copy-to-register` prefer to copy button to thing at point if on a button.

2022-10-02 09:39 UTC, matsl commented
Added a test case for inserting an `ebut` and commented out the similar test case for `ibut.` The later test case looks like it breaks due to problem with `link-to-ibut` and having a red build seems contra productive at this stage.

2022-10-02 21:11 UTC, rswgnu approved these changes

2022-10-02 22:07 UTC, rswgnu commented on hypb-register.el
> +     :file (buffer-file-name)
Yes, jump to the button source buffer and move point to the button text (label) and activate the button there.  If the source buffer is no longer live, then raise an error.

2022-10-03 21:33 UTC, matsl commented on hypb-register.el
> +     :file (buffer-file-name)
Since `insert-register` inserts an `ebut` that the user acts on would we not need a new action type then for that behavior or let `link-to-ebut` and `link-to-ibut` also handle the buffer only case?

2022-10-04 21:37 UTC, merged