Show docstring warnings again
rswgnu/hyperbole pull request #279
Opened 2022-10-07 20:29 UTC by matsl

## What

Show docstring warnings again.

## Why

When docstring warnings are gone we need to keep them under control and echoing them when byte compiling is our best option. This PR makes the build show docstring warnings for the `bin` and `eln` targets.

There is a flag that turns all warnings to errors but we have many more warnings still remaining so we are not ready for that yet I think. It can not be set to turn specific warnings to errors.

We could consider to implement our own checker that would parse (or grep) compilation output for specific warnings we want to fail the build on. For now that feels like over engineering. wdyt?

2022-10-10 03:36 UTC, rswgnu commented
> We could consider to implement our own checker that would parse (or grep) compilation output for specific warnings we want to fail the build on. For now that feels like over engineering. wdyt?

I agree.  No need now.  Let's see how it goes with the warnings re-enabled.

2022-10-10 03:38 UTC, rswgnu requested changes

2022-10-10 03:38 UTC, rswgnu commented on Makefile
> +	$(EMACS_BATCH) -f batch-byte-compile $(EL_KOTL) $(EL_COMPILE)
Would like you to save the prior version that disables docstring warnings in a comment, so we can easily re-enable it in the future if we want.  But otherwise, this is fine, so you should make that change and then just merge.

2022-10-10 21:41 UTC, matsl commented on Makefile
> +	$(EMACS_BATCH) -f batch-byte-compile $(EL_KOTL) $(EL_COMPILE)
The `bin-warn` target's default is to ignore `docstrings` warnings. That allows you to byte compile and get all the rest of the warnings if you want. Or do you want to have it available, i.e. commented our, so that the regular `bin` and `eln` targets can ignore docstrings again if we so choose?

2022-10-11 11:35 UTC, rswgnu commented on Makefile
> +	$(EMACS_BATCH) -f batch-byte-compile $(EL_KOTL) $(EL_COMPILE)
Yes, for the regular targets.  -- Bob

2022-10-11 20:29 UTC, merged