Silence warning about reference to free variable
rswgnu/hyperbole pull request #283
Opened 2022-10-12 21:33 UTC by matsl

## What

Silence warnings about referencing free variables.

## Before

```
kotl/klink.el:175:35: Warning: reference to free variable ‘smart-c-include-regexp’
kotl/kotl-mode.el:728:37: Warning: reference to free variable ‘cmpl-last-insert-location’
kotl/kotl-mode.el:729:22: Warning: reference to free variable ‘cmpl-original-string’
kotl/kotl-mode.el:730:20: Warning: assignment to free variable ‘completion-to-accept’
kotl/kview.el:481:13: Warning: assignment to free variable ‘found’
kotl/kview.el:807:54: Warning: Lexical argument shadows the dynamic variable fill-prefix
kotl/kview.el:1399:10: Warning: Variable ‘pos’ left uninitialized
hargs.el:381:33: Warning: reference to free variable ‘Info-current-node’
hargs.el:671:11: Warning: assignment to free variable ‘hargs:reading-symbol’
hargs.el:776:43: Warning: reference to free variable ‘hargs:reading-symbol’
hargs.el:782:42: Warning: reference to free variable ‘Info-current-file-completions’
hargs.el:785:51: Warning: assignment to free variable ‘Info-current-file-completions’
hload-path.el:134:9: Warning: assignment to free variable ‘generated-autoload-file’
hmouse-info.el:43:13: Warning: assignment to free variable ‘Info-complete-menu-buffer’
hmouse-info.el:49:20: Warning: reference to free variable ‘Info-complete-menu-buffer’
hmouse-info.el:238:24: Warning: reference to free variable ‘Info-complete-menu-buffer’
hmouse-info.el:381:30: Warning: reference to free variable ‘Info-complete-menu-buffer’
hmouse-drv.el:438:22: Warning: reference to free variable ‘start-window’
hmouse-sh.el:276:29: Warning: Lexical argument shadows the dynamic variable hmouse-middle-flag
hmouse-sh.el:472:30: Warning: Lexical argument shadows the dynamic variable hmouse-middle-flag
hmouse-sh.el:488:11: Warning: assignment to free variable ‘kmacro-call-mouse-event’
hpath.el:1656:27: Warning: Variable ‘modifier’ left uninitialized
hsettings.el:84:36: Warning: assignment to free variable ‘helm-allow-mouse’
hui-mouse.el:1365:26: Warning: reference to free variable ‘imenu--index-alist’
hui-mouse.el:1406:21: Warning: assignment to free variable ‘imenu--index-alist’
hui-mouse.el:1494:24: Warning: reference to free variable ‘magit-root-section’
hyrolo.el:1104:99: Warning: reference to free variable ‘child’
hyrolo.el:1284:28: Warning: reference to free variable ‘org-roam-directory’
hyrolo.el:1286:11: Warning: reference to free variable ‘org-roam-db-autosync-mode’
hyrolo.el:1844:39: Warning: reference to free variable ‘markdown-regex-header’
```

## After

```
kotl/kview.el:481:13: Warning: assignment to free variable ‘found’
kotl/kview.el:807:54: Warning: Lexical argument shadows the dynamic variable fill-prefix
kotl/kview.el:1399:10: Warning: Variable ‘pos’ left uninitialized
hmouse-sh.el:277:29: Warning: Lexical argument shadows the dynamic variable hmouse-middle-flag
hmouse-sh.el:473:30: Warning: Lexical argument shadows the dynamic variable hmouse-middle-flag
hpath.el:1656:27: Warning: Variable ‘modifier’ left uninitialized
hyrolo.el:1111:99: Warning: reference to free variable ‘child’
```

2022-10-12 21:35 UTC, matsl commented on hargs.el
> +(defvar hargs:reading-symbol nil
Could not see that this dynamic variable is defined anywhere. Should it not be that?

2022-10-12 21:37 UTC, matsl commented on kotl/kotl-mode.el
> +(defvar cmpl-last-insert-location)
What external package does these variables belong to? I tried to search the net and could not find any reference to them!?

2022-10-13 01:41 UTC, rswgnu commented on kotl/kotl-mode.el
> +(defvar cmpl-last-insert-location)
Don't know.  They should be part of maybe old versions of the emacs completion code.

2022-10-13 21:27 UTC, matsl commented on kotl/kotl-mode.el
> +(defvar cmpl-last-insert-location)
The net was the wrong place to search. I should have looked on my disk. They are part current Emacs!

2022-10-16 13:18 UTC, rswgnu requested changes

2022-10-16 13:18 UTC, rswgnu commented on hargs.el
> +(defvar hargs:reading-symbol nil
I think we really need to add tests of the behavior of each of these variables first to ensure that these defvars do not interfere with any initializations that may take place in other modules/systems, notably for non-Hyperbole variables.  Then we can apply the changes and verify things are good via the tests rather than worry about any behavior change, as some of these definitely were meant to perform with dynamic scope in the past.

2022-10-16 17:27 UTC, matsl commented on hargs.el
> +(defvar hargs:reading-symbol nil
Adding test cases is a good idea but might be overkill and I'm not sure it is that straight forward in all cases to actually test the dynamic variables. So could take some time.

The `hargs:reading-symbol` is a hyperbole variable that I suppose it used as a cache remembering the current symbol that is read so setting it to nil initially should not matter since it would be overwritten all the time. But since it is variable defined by Hyperbole IMHO it is clearer to give it an initial value than to not define it at all!?

For the other defvars they do not initialize them but define them as being in the dynamic scope, and silence the warnings. So should only make the code be more in line with the good old dynamic days. We have used this technique in the past to remove the warnings for the undefined variable that originate from other packages. Is there any way that these defvars could change behavior?

2022-10-23 15:09 UTC, rswgnu approved these changes

2022-10-23 15:09 UTC, merged