Start trying out better support for composing email
rswgnu/hyperbole pull request #290
Opened 2022-12-17 23:08 UTC by matsl

## What 

Start trying out better support for composing email.

## Why

Users need to be able to setup their favorite mail client and have it configured for editing with as little effort as possible. This is a start in exploring this for ideas and feedback.

## Discussion

This adds a new function to the email interface. A function that opens up the mail composer. The idea being that the user selects the preferred emailer and by that gets the proper setup for using email address buttons etc. 

Not sure though if that fits in there. Maybe it should be its own abstraction just for this purpose? The later would maybe make it easier for users with a strange setup to customize just the function that brings up the composer!? 

Would not the email interface be a good candidate to refactor to use the object oriented support, similar to the registry code?

2023-01-07 23:13 UTC, rswgnu commented
I'm always up for adding in good abstractions and certainly welcome improved email handling when it's ready.

2023-02-12 16:13 UTC, rswgnu requested changes

2023-02-18 09:33 UTC, matsl commented on hgnus-mail.el
> +(defun hgnus-mail--message-mail-other-window (_noerase to)
This is the implementation function used when the gnus email support is activated.

2023-02-18 09:52 UTC, matsl commented on hibtypes.el
> +
This code initialized the mail reader functionality if a user tries to use a mail link. Is not that rather subtle since the user experience is change under the hood for the user? In the gnus case the gnus news functionality will be used before using the link and gnus email functionality after.

2023-02-18 14:17 UTC, matsl commented on hibtypes.el
> +
What do you think of on Hyperbole activation giving a warning if the user has customized the email support but not initialized it?

2023-02-18 15:27 UTC, rswgnu commented
I am in favor of having a full abstraction for the email composer, as
exists for other elements of the messaging interface.

On Sat, Dec 17, 2022 at 6:09 PM Mats Lidell ***@***.***>
wrote:

> What
>
> Start trying out better support for composing email.
> Why
>
> Users need to be able to setup their favorite mail client and have it
> configured for editing with as little effort as possible. This is a start
> in exploring this for ideas and feedback.
> Discussion
>
> This adds a new function to the email interface. A function that opens up
> the mail composer. The idea being that the user selects the preferred
> emailer and by that gets the proper setup for using email address buttons
> etc.
>
> Not sure though if that fits in there. Maybe it should be its own
> abstraction just for this purpose? The later would maybe make it easier for
> users with a strange setup to customize just the function that brings up
> the composer!?
>
> Would not the email interface be a good candidate to refactor to use the
> object oriented support, similar to the registry code?
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/rswgnu/hyperbole/pull/290
> Commit Summary
>
>    - 899a79e
>    <https://github.com/rswgnu/hyperbole/pull/290/commits/899a79e21d4cc9341e3ded8a351d9ba17b7705e6>
>    Start trying out better support for composing email
>
> File Changes
>
> (5 files <https://github.com/rswgnu/hyperbole/pull/290/files>)
>
>    - *M* ChangeLog
>    <https://github.com/rswgnu/hyperbole/pull/290/files#diff-91c5b46dc84a94604a4e4d0caed9bf85590a2eddbb12d2e8dc80badf324a9dfb>
>    (11)
>    - *M* Makefile
>    <https://github.com/rswgnu/hyperbole/pull/290/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52>
>    (6)
>    - *A* hgnus-mail.el
>    <https://github.com/rswgnu/hyperbole/pull/290/files#diff-ad2ca1b79e18ca3c0354ee75ff4c72c9814e45f738fd0471cc9b40141926f8ed>
>    (78)
>    - *M* hibtypes.el
>    <https://github.com/rswgnu/hyperbole/pull/290/files#diff-b85e78cb71213fb6c7d5429ec4e2322ae8a0f0cf0faef812533f1a1c99ceb1e2>
>    (16)
>    - *M* hmail.el
>    <https://github.com/rswgnu/hyperbole/pull/290/files#diff-9d8e82ca693af05f71e9a353fa87423bc881286a95b292ad4302280e2bb94dd9>
>    (9)
>
> Patch Links:
>
>    - https://github.com/rswgnu/hyperbole/pull/290.patch
>    - https://github.com/rswgnu/hyperbole/pull/290.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/rswgnu/hyperbole/pull/290>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE5WPD6KEEP2LNM4PODOFGTWNZBY7ANCNFSM6AAAAAATCF2YNM>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-04-08 02:02 UTC, rswgnu commented on hibtypes.el
> +
If it is a customization option, then you can force the initialization function to run when the value is changed.  Would that solve this issue?

2023-04-08 02:03 UTC, rswgnu commented
We need to finish this if it is to go in the next release.

2023-10-31 14:17 UTC, matsl commented
@rswgnu Rebased to bring this on top of current master to make further development easier. I think for setting up mail sending for Gnus users this could be OK as is, but I have not thought through if the combined consequences are acceptable. Since gnus is both a mail reader and news reader we might be over complicating things supporting both in different ways.  What I mean is that if the user is used to reading news with Hyperbole and than decides to activate the mail support the reading behavior will change!? We need to think about how to resolve that I think.

2024-01-14 02:16 UTC, rswgnu commented
@matsl, just pointing out this is still out here if you want to finish this for this release.  Maybe the next one would be better.

2024-04-05 22:34 UTC, matsl commented
@rswgnu Was thinking of starting all over with this in a new PR but for now just rebased it to bring it close to master so easier to work with. Labeled with `WIP` to highlight it is not ready for review. In fact I think I need to take a step back an rethink this. Not sure we should add a mail interface to GNUS. The current news interface works well so could just keep that. Or put it this way, the reading and composing interface need to be possible to use both with GNUS and with one of the mail readers if you don't use GNUS as your mail client.

2024-06-16 13:11 UTC, matsl commented
Starting over again on this in another PR possibly using the built in support for different email composers better.

2024-06-16 13:11 UTC, closed without merging