Remove more warnings
rswgnu/hyperbole pull request #300
Opened 2023-01-29 00:11 UTC by matsl

## What

Remove more warnings

## Note

This PR removes more warnings from different places. It is split in many small commits all standalone. The changes are small though so going through the PR as normal should also work.

2023-01-29 07:22 UTC, rswgnu requested changes

2023-01-29 07:22 UTC, rswgnu commented on hib-kbd.el
> +				(not (equal key-series "")))
Two empty strings always compare 'eq' to me.  Can you create a scenario where this test fails?

2023-01-29 07:22 UTC, rswgnu commented on hib-kbd.el
> +	       (not (equal key-series "")))
Same comment as above.

2023-01-29 07:22 UTC, rswgnu commented on hibtypes.el
> +        (when (and (not (equal col-num "")) (string-match "^app/" file))
Same comment as above.

2023-01-29 07:22 UTC, rswgnu commented on hui-mini.el
> +	     (not (equal key-sequence ""))
Same comment as above.

2023-01-29 07:22 UTC, rswgnu commented on hyrolo.el
> +	(let ((hdr-pos) (num-found 0)
curr-entry-level-len was added for some work I am doing in hynote.el (not yet published) that utilizes the hyrolo.el code.  Let's leave it for now even though it is not yet used.

2023-01-29 07:22 UTC, rswgnu commented on kotl/kexport.el
> -	 (font-lock-auto-fontify) ;; Prevent syntax highlighting
Need some explanation of these removals.  Let's discuss tomorrow/today.

2023-01-29 07:22 UTC, rswgnu commented on kotl/kview.el
> -      (setq found (goto-char (- (match-end 0) 2)))
Need to discuss all the changes in this file too.

2023-01-29 09:21 UTC, matsl commented on hib-kbd.el
> +				(not (equal key-series "")))
I think this warning could originate from this page in the manual.
https://www.gnu.org/software/emacs/manual/html_node/elisp/Equality-Predicates.html

2023-01-29 09:25 UTC, matsl commented on hyrolo.el
> +	(let ((hdr-pos) (num-found 0)
OK. If possible try to avoid adding code that is not used. Just adding a comment could be enough it is work in progress so I know the purpose.

2023-01-29 09:28 UTC, matsl commented on kotl/kexport.el
> -	 (font-lock-auto-fontify) ;; Prevent syntax highlighting
It is in the commit message. From my investigation these are from XEmacs font lock and is not available in Emacs.

2023-01-29 16:25 UTC, matsl commented on kotl/kexport.el
> -	 (font-lock-auto-fontify) ;; Prevent syntax highlighting
@rswgnu Will try to find if there are any font lock functionality in current Emacs that we need to address here. Can we add that as a todo to not block this PR since holding off removing these warnings will not make current Emacs work better.

2023-01-29 17:47 UTC, rswgnu commented
Yes, will do, adding to todo list for you to research and then not
holding up the PR for this reason.

On Sun, Jan 29, 2023 at 11:26 AM Mats Lidell ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In kotl/kexport.el
> <https://github.com/rswgnu/hyperbole/pull/300#discussion_r1090002577>:
>
> > @@ -384,11 +384,7 @@ used.  Also converts Urls and Klinks into Html hyperlinks.
>  		 (buffer-name (find-file-noselect export-from)))
>  		(t (error
>  		    "(kexport:html): `%s' is an invalid `export-from' argument" export-from))))
> -	 (font-lock-auto-fontify) ;; Prevent syntax highlighting
>
> @rswgnu <https://github.com/rswgnu> Will try to find if there are any
> font lock functionality in current Emacs that we need to address here. Can
> we add that as a todo to not block this PR since holding off removing these
> warnings will not make current Emacs work better.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/rswgnu/hyperbole/pull/300#discussion_r1090002577>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE5WPDZEQR7QE57JCO5UEETWU2KZDANCNFSM6AAAAAAUJ5IOTA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-29 18:32 UTC, rswgnu commented
Asked for 3 more changes and then we should be good on this one.  See inline.

2023-01-29 22:21 UTC, matsl commented on hyrolo.el
> +	(let ((hdr-pos) (num-found 0)
Removing this commit.

2023-01-29 22:50 UTC, matsl commented
@rswgnu I think I addressed all things we talk about . PTAL

2023-01-29 22:57 UTC, rswgnu approved these changes
Just finish with the defvar comment at the bottom and I think this is ready for merging; you can just do so.

2023-02-01 22:51 UTC, matsl commented on kotl/kview.el
> -	    cell-indent
@rswgnu Came back to this first today and, since time has passed since we spoke, I'm not sure what we were thinking of here. Could it be that we make cell-indent into a defvar variable? Maybe name it with a prefix like `kview--cell-indent`?

2023-02-05 21:57 UTC, matsl commented on kotl/kview.el
> -	    cell-indent
@rswgnu As I understood today's talk I removed all things related to `cell-indent`.

2023-02-05 22:10 UTC, rswgnu approved these changes

2023-02-06 09:03 UTC, merged