Add tests for Hyperbole set library
rswgnu/hyperbole pull request #302
Opened 2023-02-05 10:48 UTC by matsl

## What

Add tests for Hyperbole set library.

## Why

Tests are good and is a start for refactoring the set library using Emacs primitives. Also raises some questions about the expected functionality in current set.el. See comments `FIXME` in the PR for discussion.

2023-02-05 14:40 UTC, rswgnu requested changes

2023-02-05 14:40 UTC, rswgnu commented on test/set-tests.el
> +(provide 'set-tests.el)
No .el

2023-02-05 14:40 UTC, rswgnu commented on test/set-tests.el
> +  (should (set:equal (set:replace 'a 'new-value-a (set:create (cons 'a 'value-a)))
Yes, replace should replace elements.

2023-02-05 14:57 UTC, rswgnu commented on test/set-tests.el
> +;;; set-tests.el --- Hyperbole set library tests                -*- lexical-binding: t; -*-
Some additional tests to add:
Test with set:equal-op set to different values.
Test that a set-like object with duplicate values is not a set.

Since you test the same sets repeatedly with non-modifying tests,
I would just store the set in a variable where applicable.

2023-02-05 21:29 UTC, matsl commented on test/set-tests.el
> +  (should (set:equal (set:remove 'a (set:create 'a 'b)) (set:create 'a 'b)))
@rswgnu I noticed this problem as well. The test case that should work is commented out and the one that works is left for illustrating what it is wrong. Remove should remove 'a from the set, right?

On add and remove. Why are they defined as macros? Can they not just be ordinary functions?

2023-02-06 07:14 UTC, rswgnu commented
Hi Mats: I did most of the updates needed in set.el including 2 new functions, then I pulled your set-tests.el and updated the comments as a number of the FIXMEs were resolved.  You just need to rebase against master and then add a few more tests in the set-tests.el file (look for remaining FIXMEs) and that should be it.

2023-02-06 20:45 UTC, matsl commented on test/set-tests.el
> +;;; set-tests.el --- Hyperbole set library tests                -*- lexical-binding: t; -*-
I suggest we can look over refactoring in a separate PR. Makes it easier to work in increments.

2023-02-06 20:51 UTC, matsl commented
@rswgnu I have added some tests but I also had to do some updates to set.el. PTAL.
I tried to generalize the tests so they could be reused with different equal operations but that turned into a mess. I would also prefer to add these tests or any other refactoring in additional PRs. 

Designing test cases for a set using `eq` is tricky. You need to think carefully when designing the test cases.

2023-02-12 16:08 UTC, rswgnu approved these changes

2023-02-12 16:16 UTC, merged