Remove some warnings
rswgnu/hyperbole pull request #306
Opened 2023-02-12 21:47 UTC by matsl

## What

Remove some warnings.

## Why

When looking at producing the set of warnings we have now I spotted a few easy fixes.

2023-02-12 21:48 UTC, matsl commented on kotl/kexport.el
> -	       i is-parent is-collapsible is-last-sibling no-sibling-stack level label contents)
Seems I added this while you removed using it so now I remove it.

2023-02-12 21:50 UTC, matsl commented on hyrolo.el
> -		  (setq curr-entry-level-len (length (buffer-substring-no-properties start (point))))
This is only set here but not used!?

Can this be code you are working on and that these var can be used later?

2023-02-13 03:59 UTC, rswgnu requested changes
All changes are fine except the one I commented on.  Remove that and we can apply this.

2023-02-13 03:59 UTC, rswgnu commented on hyrolo.el
> -		  (setq curr-entry-level-len (length (buffer-substring-no-properties start (point))))
You are correct.  This is code I inserted for compatibility with the in-development hynote.el and it is not yet finished.  Please ignore it for now and remove this change.

2023-02-13 23:09 UTC, merged