Make kotl-autoloads without building hyperbole-autoloads.el
rswgnu/hyperbole pull request #307
Opened 2023-02-15 09:27 UTC by matsl

## What

Make `kotl/kotl-autoloads` without building `hyperbole-autoloads.el`

## Why

The target `kotl/kotl-autoloads.el` has as a side effect to also build the `hyperbole-autoloads.el.` That is not correct and can lead to unexpected problems and even errors. Patch by Stefan Monnier.  This PR fixed this so that only `kotl-autoloads` are produced as a result of that make target.

2023-02-15 12:22 UTC, rswgnu requested changes

2023-02-15 12:22 UTC, rswgnu commented on Makefile
> +	$(EMACS_PLAIN_BATCH) --debug --eval "(progn (setq generated-autoload-file (expand-file-name \"kotl/kotl-autoloads.el\") backup-inhibited t) (let (find-file-hooks) (make-directory-autoloads \"kotl/\"
This breaks versions of Emacs that I have tested in the past that lack make-directory autoloads.  I will have to see if it is true of 27.1.  If not, then we can use it.

2023-02-15 23:36 UTC, matsl commented on Makefile
> +	$(EMACS_PLAIN_BATCH) --debug --eval "(progn (setq generated-autoload-file (expand-file-name \"kotl/kotl-autoloads.el\") backup-inhibited t) (let (find-file-hooks) (make-directory-autoloads \"kotl/\"
Oh, you are right. That can be true. The interesting part is that the scraping for autoloads works for all our versions we use here but I don't think it uses that target. We don't build for 21.1 though. Only 27.2. I'll add a test to check.

2023-02-16 00:01 UTC, matsl commented on Makefile
> +	$(EMACS_PLAIN_BATCH) --debug --eval "(progn (setq generated-autoload-file (expand-file-name \"kotl/kotl-autoloads.el\") backup-inhibited t) (let (find-file-hooks) (make-directory-autoloads \"kotl/\"
The test proves it breaks on 27.2. I'll see if I can fix a workaround.

2023-02-16 23:37 UTC, matsl commented on Makefile
> +	$(EMACS_PLAIN_BATCH) --debug --eval "(progn (setq generated-autoload-file (expand-file-name \"kotl/kotl-autoloads.el\") backup-inhibited t) (let (find-file-hooks) (make-directory-autoloads \"kotl/\"
@rswgnu The autoload generation for kotl now fallbacks to Emacs 27 functionality.

2023-02-17 00:27 UTC, rswgnu approved these changes

2023-02-17 07:43 UTC, merged