Fix html checker warnings for kotl export
rswgnu/hyperbole pull request #313
Opened 2023-03-04 15:00 UTC by matsl

## What

Fix html checker warnings for kotl export.

## Why

Generated HTML should be up to standards. 

## Note

This is work in progress. There are more errors to address. The remaining issues fall in four categories:
1. Attributes in html is deprecated and should be moved to css instead
2. Font element is deprecated and should be moved to css instead
3. Elements not allowed as child of another element
4. Misc minor errors

2023-03-11 03:22 UTC, rswgnu commented
Hi Mats:  The main concern is any change in visual appearance.  Can you do a before and after set of screen shots that you think represents any change decently.  If the look is reasonable, I am fine with applying this, though I would prefer all the FIXMEs be gone prior to a merge if possible.

2023-03-11 09:57 UTC, matsl commented
@rswgnu Added the generated html to the branch so we can review how the output looks. You can compare the difference by running the export in the master branch locally. I hope that this works. 

When we are ready to merge this we shall remove the file. That is the best way I could come up with now for easy review and update. (Open for other suggestions.)

Regarding the FIXMEs they ask review questions but I'm happy to resolve them in the simplest way if you have no big concerns on them.

2023-03-11 17:30 UTC, rswgnu requested changes

2023-03-11 17:30 UTC, rswgnu commented on kotl/kexport.el
>  (defcustom kexport:html-body-attributes
I think you should be able to customize this from Lisp.  What is the problem here if we leave it as is?

2023-03-11 17:30 UTC, rswgnu commented on kotl/kexport.el
> +;; this '&quot'
This change is fine and the FIXME can be removed.  I am adding changes so &quot; will be recognized as path and Info-node delimiters when editing HTML in Emacs.

Another level of improvement would be if we turned these into hrefs that pointed to the GNU HTML versions of their Texinfo manuals.  See https://www.gnu.org/manual/manual.en.html.

2023-03-11 17:30 UTC, rswgnu commented on kotl/kexport.el
> +        if(currentState=='none')
Why not this whitespacing style:  "if (currentState == 'none')"?

Is it wrong?

2023-03-11 17:30 UTC, rswgnu commented on kotl/kexport.el
> +	(princ "<html lang=\"en\">\n")
You are welcome to add a variable but we support English only thoughout Hyperbole, so...

2023-03-11 17:30 UTC, rswgnu commented on kotl/kexport.el
> +	;; (princ "<div id=\"top\"></div><div id=\"k0\"></div>\n")
k0 represents the invisible top node of the outline that all level1 cells are children of.  It can have properties attached to it, which likely should be exported as meta data attached in the HTML header, though there may not presently be any code for that.

2023-03-11 17:30 UTC, rswgnu commented on test/kexport-tests.el
>    (let* ((kotl-file (make-temp-file "hypb" nil ".kotl"))
Nice improvements here.

2023-03-11 22:05 UTC, rswgnu commented
Hi @Lidell Mats ***@***.***>:

I see 3 issues with the new HTML output when compared with the old:

1. The autogenerated cell number font-size is larger than the text size and
therefore too big.

2. There were some very tricky vertical spacing issues between cells that
we had solved.  They are now back in your new version and the cells are
separated by extra whitespace that does not look good.

3. Mouse over highlighting on collapsible tree parent cells no longer
works, so it is harder to tell there is dynamic behavior there.

On Sat, Mar 11, 2023 at 4:57 AM Mats Lidell ***@***.***>
wrote:

> @rswgnu <https://github.com/rswgnu> Added the generated html to the
> branch so we can review how the output looks. You can compare the
> difference by running the export in the master branch locally. I hope that
> this works.
>
> When we are ready to merge this we shall remove the file. That is the best
> way I could come up with now for easy review and update. (Open for other
> suggestions.)
>
> Regarding the FIXMEs they ask review questions but I'm happy to resolve
> them in the simplest way if you have no big concerns on them.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/rswgnu/hyperbole/pull/313#issuecomment-1464875122>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE5WPD7P52UZRFRCM3FDDCTW3REBLANCNFSM6AAAAAAVPS3VWM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-03-11 22:58 UTC, matsl commented on kotl/kexport.el
>  (defcustom kexport:html-body-attributes
1. [body](https://www.w3schools.com/tags/tag_body.asp) does only support the [global attributes.](https://www.w3schools.com/tags/ref_standardattributes.asp) 
2. It is therefore not used in the code at the moment (so should really be removed in this form.)

So should ideally go into the css definition. I have not looked at what would be the best way to do that. One option would be to make the whole css customizable, another to just customize one attribute i.e. `html-body-bgcolor` etc, a third have some smarter template where multiple attributes can be set or overridden. Like a defauilt css and then add another css that will override the defaults.

2023-03-11 23:04 UTC, matsl commented on kotl/kexport.el
> +        if(currentState=='none')
Code is copied from html tutorial and only modified with what I needed. Did not bother about the code style. Will check if it matters and update if not.

2023-03-11 23:10 UTC, matsl commented on kotl/kexport.el
> +	(princ "<html lang=\"en\">\n")
Hardcoding is fine now so I will stick with that.

2023-03-11 23:16 UTC, matsl commented on kotl/kexport.el
> +	;; (princ "<div id=\"top\"></div><div id=\"k0\"></div>\n")
If I get it right then it does not led itself to have any tag like this. It should rather go into <head> than <body>. So it can be removed for now?

2023-03-11 23:31 UTC, matsl commented on kotl/kexport.el
> +        if(currentState=='none')
Changed to more readable code.

2023-03-11 23:55 UTC, matsl commented
@rswgnu Thanks for the review.

Sorry for maybe not setting the right expectations. The goal of this iteration was to create legal HTML that would have the right functionality and then focus on the css styling.

> The autogenerated cell number font-size is larger than the text size and
therefore too big.

That was a deliberate choice in this increment so I could see that I could manipulate the style with css. Will of course set this to what ever value we see fit. (Plus I rather like a bigger font on the cell numbers. ;-) 

> There were some very tricky vertical spacing issues between cells that
we had solved.  They are now back in your new version and the cells are
separated by extra whitespace that does not look good.

My plan is to solve these issues with changes to css. It was to hard to do that while working on the list structure together with getting the collapsible to work so I paused it for later.

> Mouse over highlighting on collapsible tree parent cells no longer
works, so it is harder to tell there is dynamic behavior there.

That has not been implemented yet either. I will add that soon when I work on the styling.

2023-03-12 00:31 UTC, rswgnu commented
Got it, thanks.  Let me know when you are through these and I'll have
another look.  Thanks.

On Sat, Mar 11, 2023 at 6:55 PM Mats Lidell ***@***.***>
wrote:

> @rswgnu <https://github.com/rswgnu> Thanks for the review.
>
> Sorry for maybe not setting the right expectations. The goal of this
> iteration was to create legal HTML that would have the right functionality
> and then focus on the css styling.
>
> The autogenerated cell number font-size is larger than the text size and
> therefore too big.
>
> That was a deliberate choice in this increment so I could see that I could
> manipulate the style with css. Will of course set this to what ever value
> we see fit. (Plus I rather like a bigger font on the cell numbers. ;-)
>
> There were some very tricky vertical spacing issues between cells that
> we had solved. They are now back in your new version and the cells are
> separated by extra whitespace that does not look good.
>
> My plan is to solve these issues with changes to css. It was to hard to do
> that while working on the list structure together with getting the
> collapsible to work so I paused it for later.
>
> Mouse over highlighting on collapsible tree parent cells no longer
> works, so it is harder to tell there is dynamic behavior there.
>
> That has not been implemented yet either. I will add that soon when I work
> on the styling.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/rswgnu/hyperbole/pull/313#issuecomment-1465052312>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE5WPD4Z7KTR5MCA37VXJK3W3UGF7ANCNFSM6AAAAAAVPS3VWM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-03-12 16:20 UTC, merged