Silence various byte compiler warnings
rswgnu/hyperbole pull request #320
Opened 2023-04-23 20:45 UTC by matsl

## What

Fix a mix of different types of byte compiler warnings.

## Why

Taking yet another stab at getting the warnings down to a low number.

2023-04-24 01:42 UTC, rswgnu requested changes

2023-04-24 01:42 UTC, rswgnu commented on hbdata.el
>  Utilize arguments LBL-KEY, KEY-SRC and optional DIRECTORY."
Need to rename args here too with underscore.

2023-04-24 01:42 UTC, rswgnu commented on hui-mouse.el
> +selected helm item."
First doc line has to be complete by itself, so that apropos works properly.

2023-04-24 01:42 UTC, rswgnu commented on hycontrol.el
> +FULL-FLAG is non-nil.  PATTERN is a shell glob pattern.
Make first line standalone.

2023-04-24 01:42 UTC, rswgnu commented
Looks good, otherwise.

2023-04-24 21:57 UTC, matsl commented on hbdata.el
>  Utilize arguments LBL-KEY, KEY-SRC and optional DIRECTORY."
Good catch. Thanks. Maybe remove them from the doc since they are not used?

2023-04-24 21:58 UTC, matsl commented on hui-mouse.el
> +selected helm item."
I understand. For this PR though - The firs line is not changed.

2023-04-24 22:00 UTC, matsl commented on hycontrol.el
> +FULL-FLAG is non-nil.  PATTERN is a shell glob pattern.
Same here. First line is not altered.

2023-04-24 22:43 UTC, rswgnu commented on hycontrol.el
> +FULL-FLAG is non-nil.  PATTERN is a shell glob pattern.
But the last part of the first line shows up in the changed lines as part of the second line, so the line is getting wrapped on you somehow.

2023-04-24 22:44 UTC, rswgnu commented on hbdata.el
>  Utilize arguments LBL-KEY, KEY-SRC and optional DIRECTORY."
I am not sure why those args are there then; maybe copied from the ebut function of the same kind and then called from an hbut genetic fun tion that requires the same signature.  Fine to remove them from the doc.

2023-04-25 22:13 UTC, matsl commented on hbdata.el
>  Utilize arguments LBL-KEY, KEY-SRC and optional DIRECTORY."
Yes, We can look at that separately. I will remove them from the docs for now.

2023-04-25 22:16 UTC, matsl commented on hycontrol.el
> +FULL-FLAG is non-nil.  PATTERN is a shell glob pattern.
Is not line 1740 the first line? "Display up to an abs(prefix ARG)-sized window grid of files matching PATTERN."?

2023-04-26 00:18 UTC, rswgnu commented on hycontrol.el
> +FULL-FLAG is non-nil.  PATTERN is a shell glob pattern.
Oh, the first line was elided, so I was commenting on the second line by mistake.  Appoved now.

2023-04-27 00:26 UTC, rswgnu commented
It won't let me.  Just merge.

2023-04-27 06:45 UTC, matsl commented
Hi Bob,

Ok. Thanks for trying. Will merge.

Yours

Robert Weiner ***@***.***> skrev: (27 april 2023 02:26:31 CEST)
>It won't let me.  Just merge.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/rswgnu/hyperbole/pull/320#issuecomment-1524283893
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
## Mats

2023-04-27 17:50 UTC, merged