Stefan scratch hyperbole updates
rswgnu/hyperbole pull request #322
Opened 2023-05-01 14:56 UTC by matsl

## What

Stefan updates from scratch hyperbole branch on elpa rebased onto master.

## Why

Before splitting in smaller pieces I supply the full patch as one PR since I think going over each commit might speed things up. I think each commit stands out quite well on its own with only small dependencies between the commits. If you can review this PR and suggest what commit to pick from it I can create new PRs for those. 

Some of the changes comes in the form of  FIXMEs so is something we might want to address rather than commit?

2023-05-07 12:58 UTC, rswgnu requested changes

2023-05-07 12:58 UTC, rswgnu commented on hbut.el
> +			 (if hui--ignore-action-key-depress-prev-point
Unsure about this change, have to look at it more.  If I view a file and don't add a comment, that means it is good for a PR (once I submit my review).  -- rsw

2023-05-07 12:58 UTC, rswgnu commented on hibtypes.el
> +;; FIXME: The `mail-' prefix does not belong to Hyperbole!
I'm fine with adding an hypb- prefix here.

2023-05-07 12:58 UTC, rswgnu commented on hui-mouse.el
>  (declare-function todotxt-archive "ext:todotxt")
We can't merge any FIXMEs but have to decide on handling each one.

2023-05-07 12:58 UTC, rswgnu commented on hui-mouse.el
> +			            ;; FIXME: Use Emacs-27's `flatten-tree'?
Would be fine with flatten-tree.

2023-05-07 12:58 UTC, rswgnu commented on hui.el
> +      (let ((hui--ignore-action-key-depress-prev-point t)
These flags seem to pop up many places; seems like additional complexity to me on first glance.

2023-05-07 12:58 UTC, rswgnu commented on hui.el
> +	;; FIXME: Move this error to the `interactive' spec?
Sounds reasonable.

2023-05-07 12:58 UTC, rswgnu commented on hversion.el
> -
I always thought this was pretty good and useful code.  Of course, if we don't need to call it, it would be good but we'll really have to look at the logic to be sure flags can achieve the same affect without having to annotate the code in many new places.

2023-05-07 12:58 UTC, rswgnu commented on hypb.el
>         (error "Start buffer, '%s', is not live" (current-buffer)))
I doubt I added this without seeing the need for it first.  Maybe look at whether it can be better written.

2023-05-07 12:58 UTC, rswgnu commented on kotl/kotl-mode.el
> +	     ;;(not (hyperb:stack-frame '(kcell-view:to-label-end)))
Just need to look at this to ensure does not break anything.

2023-05-07 12:58 UTC, rswgnu commented on kotl/kview.el
> +  ;; FIXME: A.k.a (invisible-p (or pos (point)))
If invisible-p covers the same cases, we can get rid of this, just inspect its implementation.

2023-05-07 12:58 UTC, rswgnu commented on kotl/kview.el
>    (when (re-search-forward "[\n\r]" nil 'move)
Makes sense; just have to be clear when to use visible vs non-visible lines, so do not break things.

2023-05-28 08:54 UTC, matsl commented on hibtypes.el
> +;; FIXME: The `mail-' prefix does not belong to Hyperbole!
Extracted into a separate [PR](https://github.com/rswgnu/hyperbole/pull/336)

2023-05-28 09:54 UTC, matsl commented on kotl/kview.el
> +  ;; FIXME: A.k.a (invisible-p (or pos (point)))
For discussion see [PR](https://github.com/rswgnu/hyperbole/pull/337)

2023-05-28 14:45 UTC, rswgnu approved these changes

2023-06-22 07:12 UTC, matsl commented
Closing this as it is superseded by #343

2023-06-22 07:12 UTC, closed without merging