Stefan scratch hyperbole 20230621
rswgnu/hyperbole pull request #343
Opened 2023-06-21 21:42 UTC by matsl

## What

Stefans latest updates patch with Makefile update.

## Why

Put up Stefans changes again for review.

2023-06-22 03:07 UTC, rswgnu requested changes

2023-06-22 03:07 UTC, rswgnu commented on hversion.el
> +    (set-frame-parameter frame 'hyperb:window-system term)
My recollection is that we wanted just the first part of this term value for simpler comparisons but I don't have strong opinions on this.

2023-06-22 03:07 UTC, rswgnu commented on hversion.el
>    (frame-parameter frame 'hyperb:window-system))
Probably, just seemed simpler than going through a bunch of conditionals each time it was used.

2023-06-22 03:07 UTC, rswgnu commented on hversion.el
>  		   (if (and file (setq file (hpath:substitute-value file)))
Rest is fine.

2023-06-22 03:07 UTC, rswgnu commented on Makefile
> +LOAD_EL = $(EL_KOTL:%.el=-l ./%.el) $(EL_COMPILE:%.el=-l ./%.el)
Will this work with non-GNU make?  We want that support.

2023-06-24 08:02 UTC, matsl commented on hactypes.el
> +      (set-buffer buf-name)
@rswgnu This is odd. `select-buffer` does not exist in any version of Emacs. So the old code is broken. What do you think of keeping this change and work on fixing the rfc-toc function in separate PRs?

2023-06-25 16:12 UTC, merged

2023-06-28 03:36 UTC, monnier commented on hversion.el
>    (frame-parameter frame 'hyperb:window-system))
It's definitely no simpler since recomputing it on-the-fly means extracting the computation into its own function and throwing away everything else :-)

2023-06-28 03:39 UTC, monnier commented on hyperbole.el
> +
The main purpose of this code is not to be executed when `hyperbole.el` is loaded but when `hyperbole-autoloads.el` is loaded, i.e. at Emacs startup (thanks to the autoload cookie).

2023-06-28 03:42 UTC, monnier commented on hbut.el
> -
The `(indent defun)` in the `declare` statement in the definition of `defib`.

2023-06-28 03:43 UTC, monnier commented on hyrolo.el
> +  :type 'string)
They're redundant because they specify the group defined earlier in the file, which is used by default in the absence of a `:group`.