Remove redundant :group args and obsolete * in defcustom docstrings
rswgnu/hyperbole pull request #353
Opened 2023-06-29 22:07 UTC by matsl

## What

`:group` args are redundant and `*` is obsolete in `defcustom` docstrings.

Contribution from Stefan Monnier. Thanks Stefan.

See: https://github.com/rswgnu/hyperbole/pull/343/files#r1244628372

2023-07-01 16:26 UTC, rswgnu requested changes

2023-07-01 16:26 UTC, rswgnu commented on hyrolo.el
> -  :group 'hyperbole-rolo)
I want to group all hyperbole customizations together under 'hyperbole-' groups.  It seems to me if you remove this, the group for customizations here would be 'hyrolo', so it would not match this standard.  You could test it out but I think Stefan is just thinking that the grouping should match the filename rather than some broader linkage of customizations.

2023-07-01 21:36 UTC, matsl commented on hyrolo.el
> -  :group 'hyperbole-rolo)
I think the defgroup `hyperbole-rolo` creates the grouping that you want. hyperbole-rolo is a group that is a subgroup of hyperbole. hyperbole-rolo is then default for all the defcustom.

This is how the custom settings look after the change. (Byte compiled the branch and restarted Emacs. That would be enough to see the new settings I think.)

![bild](https://github.com/rswgnu/hyperbole/assets/2061650/863e829a-9bf9-4a27-8a39-41d4195be276)

![bild](https://github.com/rswgnu/hyperbole/assets/2061650/9fabccf2-78bf-44b8-bd83-2c9adc6ee302)

2023-07-02 02:09 UTC, rswgnu commented
Ok, great.-- BobOn Jul 1, 2023, at 5:36 PM, Mats Lidell ***@***.***> wrote:﻿
@matsl commented on this pull request.



In hyrolo.el:
>  Default is American style.  See documentation of the function
 `format-time-string' for format options."
-  :type 'string
-  :group 'hyperbole-rolo)

I think the defgroup hyperbole-rolo creates the grouping that you want. hyperbole-rolo is a group that is a subgroup of hyperbole. hyperbole-rolo is then default for all the defcustom.
This is how the custom settings look after the change. (Byte compiled the branch and restarted Emacs. That would be enough to see the new settings I think.)



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because your review was requested.Message ID: ***@***.***>

2023-07-02 03:56 UTC, rswgnu approved these changes
Approved with changes requested.

2023-07-02 03:56 UTC, rswgnu commented on ChangeLog
> +* hyrolo.e: Remove redundant `:group` args.  Remove obsolete `*` in
Missing 'l' on .el.

2023-07-02 03:56 UTC, rswgnu commented on hyrolo.el
> -  :type 'string
Missing the add back of the :type line here?

2023-07-02 08:07 UTC, matsl commented on hyrolo.el
> -  :type 'string
I don't understand the comment. The `:type` line kept!?

2023-07-02 08:09 UTC, rswgnu commented
All the other places, the :type line was left in (or added back in the
diff).  Here it just seems to be deleted.

On Sun, Jul 2, 2023 at 4:08 AM Mats Lidell ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In hyrolo.el
> <https://github.com/rswgnu/hyperbole/pull/353#discussion_r1249340158>:
>
> >  Default is American style.  See documentation of the function
>  `format-time-string' for format options."
> -  :type 'string
>
> I don't understand the comment. The :type line kept!?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/rswgnu/hyperbole/pull/353#discussion_r1249340158>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE5WPD24V7AH5IGFCSRPFODXOET6TANCNFSM6AAAAAAZZCKFTE>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-07-02 08:12 UTC, merged

2023-07-02 08:23 UTC, matsl commented
OK. I have merged the PR now. I'll make a note of that and take a look later.

2023-07-02 08:26 UTC, matsl commented
Later is now. I went to the master branch and it looks like it is still there. https://github.com/rswgnu/hyperbole/blob/ac6e50e3ecf98017999d43808ac8cab50d84278f/hyrolo.el#L77