Remove some byte compilation warnings
rswgnu/hyperbole pull request #354
Opened 2023-06-30 20:58 UTC by matsl

## What

Remove some byte compilation warnings

## Details

* hui.el:
  hpath.el:
  hbut.el:
  hbdata.el: Fix single quotes in docstrings.

* kotl/kview.el (kcell-view:to-label-end): Add missing point to error
    message.

* hactypes.el (require): Load hsys-org for org-fold-show-context.
    (link-to-org-id-marker): Use org-fold-show-context.
    (link-to-org-id): Silence byte compile warnings when org-roam not loaded.

2023-06-30 21:32 UTC, matsl commented on kotl/kview.el
> +	  (t (error "(kcell-view:to-label-end): In cell at pos %d, can't find end of cell's label" (or pos (point)))))))
Copied `(or pos (point))` construct from line 497 but should maybe just be `(point)` here?

2023-07-01 16:19 UTC, rswgnu requested changes

2023-07-01 16:19 UTC, rswgnu commented on hactypes.el
> +  "Do implicit button action specified by NAME-KEY, optional BUT-SRC and POINT.
'Do' does not read as well.  We could use 'Execute' if you prefer that to 'Perform'.

2023-07-01 16:19 UTC, rswgnu commented on hactypes.el
>  	  (inhibit-message t)) ;; Inhibit org-id-find status msgs
Shouldn't this inhibit-message binding inhibit warnings from the org-roam-id-find call?

2023-07-01 16:19 UTC, rswgnu commented on hactypes.el
> +    (org-fold-show-context))
This is not built-in to Emacs 27.1 so we should not update it.  For built-in packages, we always need to check this rather than listening to the package updates about what is obsolete; otherwise, we will break things for people who have not yet updated.

2023-07-01 16:19 UTC, rswgnu commented on kotl/kview.el
> +	  (t (error "(kcell-view:to-label-end): In cell at pos %d, can't find end of cell's label" (or pos (point)))))))
(or pos (point)) - looks right.

2023-07-01 20:41 UTC, matsl commented on hactypes.el
> +  "Do implicit button action specified by NAME-KEY, optional BUT-SRC and POINT.
The change is for removing a byte compile warning. The line is too long and causes a 80-char warning. So Execute does unfortunately not resolve that. So we need to cut it down some how. Using Do was the best I could think of. Feel free to suggest any other way to make the line shorter.

2023-07-01 20:47 UTC, matsl commented on hactypes.el
>  	  (inhibit-message t)) ;; Inhibit org-id-find status msgs
If org-roam is not loaded there is warning about org-roam-id-find not being available. I choose to use the no-warning here but I guess we could also declare org-roam-id-find as we have done for other external packages not necessary available.  Do you prefer that?

2023-07-01 20:55 UTC, rswgnu requested changes

2023-07-01 20:55 UTC, rswgnu commented on hactypes.el
> +  "Do implicit button action specified by NAME-KEY, optional BUT-SRC and POINT.
Activate implicit button given by NAME-KEY, optional BUT-SRC and POINT.

2023-07-01 20:55 UTC, rswgnu commented on hactypes.el
>  	  (inhibit-message t)) ;; Inhibit org-id-find status msgs
Yes, use the declaration instead.  Thanks.

2023-07-01 20:56 UTC, matsl commented on hactypes.el
> +    (org-fold-show-context))
We have already taken this step by provide compatibility code in [hsys-org](https://github.com/rswgnu/hyperbole/blob/a19a1e1d278a654aa7a7d27fdcbdd4b5ff01adba/hsys-org.el#L86) hence the reason to require hsys-org to get this definition. Is it not best if we move to the new definition in one part of the code to do it everywhere?

Using the type of compatibility code that we have there looks to me as a good way to resolve the issues with obsolete functions.

2023-07-02 02:00 UTC, rswgnu commented on hactypes.el
> +    (org-fold-show-context))
Ok, sounds fine but I am running the latest Hyperbole and did not see a def for that function.  Let me check what is happening.

2023-07-02 04:00 UTC, rswgnu commented on hactypes.el
> +    (org-fold-show-context))
Ok, the hsys-org.el aliasing looks fine.

2023-07-02 04:05 UTC, rswgnu approved these changes

2023-07-02 08:00 UTC, merged