Preload `kotl-autoloads`
rswgnu/hyperbole pull request #355
Opened 2023-06-30 22:08 UTC by matsl

## What

* hyperbole.el: Preload `kotl-autoloads`

2023-06-30 22:54 UTC, rswgnu requested changes

2023-06-30 22:54 UTC, rswgnu commented on hyperbole.el
> +    ;; FIXME: Contrary to the usual ELPA autoloads files, `kotl-autoloads'
Remove the FIXME word, this is just a comment.  If there is some way to make this happen in the autoload file, we should but I don't know what is different there compared to the Hyperbole one.

2023-07-01 08:27 UTC, matsl commented on hyperbole.el
> +;; Last-mod:      1-Jul-23 at 10:12:06 by Mats Lidell
@rswgnu Noticed now that out header support does not handle the alignment properly and that one number dates does not get prefixed with a leading 0 as seem to be the standard from the past. Something that we should fix?

2023-07-01 08:42 UTC, matsl commented on hyperbole.el
> +;; Last-Mod:      1-Jul-23 at 10:33:45 by Mats Lidell
Updated field tag to `Last-Mod` with capital M, which is what we have in all other files, which led to that my comment about the date format got lost from the PR. So repeating it here.

@rswgnu Noticed that we for dates with one digit do not prefix with a leading zero that we have a for the Created date. So looks a bit odd. This is of course a minor thing. Not sure i we want to fix it and what would be the appropriate fix - add leading zero or remove leading zero from the Created field?

There is also an issue with the alignment that we might want to fix in the header update code. Also that a minor of course.

2023-07-01 16:28 UTC, rswgnu commented on hyperbole.el
> +;; Last-mod:      1-Jul-23 at 10:12:06 by Mats Lidell
Padding with a space like you show here so the dates still align is fine.  Are the dates not aligning properly now?

2023-07-01 16:30 UTC, rswgnu commented on hyperbole.el
> +;; Last-Mod:      1-Jul-23 at 10:33:45 by Mats Lidell
I think for single digit dates, using a space to pad is best.  If Mod needs to be capitalized to work properly, then please fix it.  I am open to any code changes that fix bugs.

2023-07-01 16:30 UTC, rswgnu approved these changes

2023-07-01 21:19 UTC, matsl commented on hyperbole.el
> +;; Last-Mod:      1-Jul-23 at 10:33:45 by Mats Lidell
We have Last-Mod with capital M in all files except here in hyperbole.el.

The alignment I'm referring to is the alignment with the other fields. Seems we have the "args" part moved further to the right here in hyperbole.el and that is causing the issue.

2023-07-01 21:19 UTC, merged