Add koutline tests
rswgnu/hyperbole pull request #359
Opened 2023-07-07 23:17 UTC by matsl

## What 

Add koutline tests.

2023-07-07 23:20 UTC, matsl commented on test/kotl-mode-tests.el
> +(ert-deftest kotl-mode-move-up-to-first-line ()
@rswgnu This test fails due to error is signaled when moving up to first line. I think this is a bug. wdyt?
The test is run in interactive mode so does not affect the CI build. So I added it to not forget it.

2023-07-08 14:02 UTC, rswgnu requested changes

2023-07-08 14:02 UTC, rswgnu commented on test/kotl-mode-tests.el
> +(ert-deftest kotl-mode-move-up-to-first-line ()
I just tested trying to move to the previous line from the first line in kotl-mode and in another mode.  Both basically behaved the same.  With debug-on-error t, both beep and display a message but do not show a backtrace because they are not actually triggering an error (just look at the code for kotl-mode:previous-line).  Try it with a test yourself.  So if there is an issue it seems it would be with the test.

2023-07-08 16:55 UTC, matsl commented on test/kotl-mode-tests.el
> +(ert-deftest kotl-mode-move-up-to-first-line ()
@rswgnu The test is moving up to the first line from the `second` line. There is another test case for trying to move to the previous line form the first line.

2023-07-08 18:37 UTC, rswgnu commented on test/kotl-mode-tests.el
> +(ert-deftest kotl-mode-move-up-to-first-line ()
Ok, I understand now.  Will have a look.

2023-07-08 18:45 UTC, rswgnu commented on test/kotl-mode-tests.el
> +(ert-deftest kotl-mode-move-up-to-first-line ()
You changed hte name to 'kotl-mode-move-up-from-first-line' and you don't insert a newline in this test so point ends on the first line and should indeed beep when you try to move up.  Maybe you have another test that moves from the second line.

2023-08-29 16:18 UTC, rswgnu commented
Let's figure out how to close this PR out.  Thanks.

2023-10-07 09:37 UTC, rswgnu commented
> Let's figure out how to close this PR out. Thanks.

Hi Mats:  could you resolve the final with-mock issue here or test again?

2023-10-07 09:42 UTC, matsl commented
Hi  @rswgnu, Yes. Thanks for the reminder. I will take a look.

2023-10-08 23:06 UTC, matsl commented
Hi @rswgnu, I reworked the PR a bit to make the tests clearer. Not sure what was the issue before. Maybe the should-error construct  for mocks that ate **not** called is a bit convoluted but it is one way to verify that functions are not being called. Maybe `flet` is a better machinery for that but not sure since that would require more code.

2023-10-09 00:15 UTC, rswgnu approved these changes

2023-10-09 21:58 UTC, merged