Remove compiler warnings introduced lately
rswgnu/hyperbole pull request #390
Opened 2023-10-05 21:20 UTC by matsl

## What

Remove compiler warnings introduced lately. These are the last easy warning to remove.

## Why

We want hyperbole to compile with not warnings.

2023-10-05 21:26 UTC, matsl commented on hui.el
> +      (when (and name-arg-flag (not (equal name-arg-flag '(4))) (not name-key))
This is the warning about the potential problem with eq not giving the expected behavior since atoms might not be the same although their value is the same.

Odd thing is:
```
(eq '(4) '(4)) => nil
```
Which makes me wonder how this code is supposed to work. We also have many test cases which uses eq with constants that should not be trusted but seems to work!? Maybe you know.

Anyway I think using equal is a small price for not getting the warning.

2023-10-05 21:29 UTC, rswgnu commented on hui.el
> +      (when (and name-arg-flag (not (equal name-arg-flag '(4))) (not name-key))
You are right, good catch.  Two instances of the same atom like nimbers ir symbols will compare eq but two lists of the same number will not, so this was just wrong and I imagine never triggering.

2023-10-05 21:35 UTC, rswgnu requested changes

2023-10-05 21:35 UTC, rswgnu commented on hui-mouse.el
> +(require 'eieio)
We should not be using this library.  Let’s eliminate any dependency on it.  How could the code have been running if this were necessary?

2023-10-05 21:35 UTC, rswgnu commented on hui-mouse.el
> +
Sorry, don’t want this in.  Not a fan of the complexity therein.

2023-10-05 21:57 UTC, matsl commented on hui-mouse.el
> +
It comes from `magit` that uses `eieio` `slots` that we touch. So far I have not found any other way to remove the warnings for the slots. So it is either this or getting the warnings for the slots. [Check earlier build.](https://github.com/rswgnu/hyperbole/actions/runs/6423671655) to see how it look.

So we are not using anything additional in there I think. It is just being able to add the slots we use to the known slot names.

Now you know. I agree it looks a bit dirty but the warnings do stick out too. With few warnings the ones that are left get more space! ;-)

All in all I have no big issue with removing this. Just wanted to make it clear the reason for why it is needed.

2023-10-05 23:05 UTC, rswgnu commented
Yes, I think just wrap an eval-when-compile around the require and we should be good.-- BobOn Oct 5, 2023, at 10:57 PM, Mats Lidell ***@***.***> wrote:﻿
@matsl commented on this pull request.



In hui-mouse.el:
> @@ -1532,6 +1533,11 @@ If assist-key is pressed:
 	       (magit-section-cycle-global)
 	     (smart-magit-display-file (key-binding (kbd "RET"))))))))
 
+;; Silence compiler about unknown slot. From eieio-tests.el
+(eval-when-compile
+  (dolist (slot '(content washer hidden start))
+    (cl-pushnew slot eieio--known-slot-names)))
+

It comes from magit that uses eieio slots that we touch. So far I have not found any other way to remove the warnings for the slots. So it is either this or getting the warnings for the slots. Check earlier build. to see how it look.
So we are not using anything additional in there I think. It is just being able to add the slots we use to the known slot names.
Now you know. I agree it looks a bit dirty but the warnings do stick out too. With few warnings the ones that are left get more space! ;-)
All in all I have no big issue with removing this. Just wanted to make it clear the reason for why it is needed.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

2023-10-06 23:11 UTC, rswgnu approved these changes

2023-10-07 08:10 UTC, merged