Verify number of global ibuts and ebuts
rswgnu/hyperbole pull request #394
Opened 2023-10-11 12:46 UTC by matsl

## What

Verify number of global ibuts and ebuts.

## Why

Noticed a bug in `hbdata:to-entry-buf` where we for ebuts look into the `Hyperbole mail mode` (That are mail and news related modes like Gnus summary mode, message mode etc.) Global buttons should not be affected by what mode we are currently in.

This adds a set of test cases that works and one that pin points the error. It is set as expected failure so not to cause CI/CD to break.

2023-10-11 12:48 UTC, matsl commented on test/hui-tests.el
> +  :expected-result :failed
@rswgnu This is the case that fails. One global ebut is created but it is not listed since we look for ebut data in the message-mode file.

2023-10-18 21:47 UTC, matsl commented
@rswgnu Refactored `hbdata:to-entry-buf` into smaller methods so that one of them can be used for the global button data without having to consider the case with button data in buffer. I think that is cleaner than to have a check for the global button file. 

However there is room for improvements. I'm not happy about the method that checks if we are in a buffer for which the but data is stored in buffer. It has to have the side effect of moving to the but data buffer as well as checking. Maybe that can be made better by looking more globally how this function is used!?

Anyway, this is how it looks now. PTAL. And yes I used the prefix `hbdata` but used the standard naming convention with the dashes for internal functions. YMMW.

Most important the test case works now so I have removed the expected failure setting. It is now expected to work!

2023-10-21 22:33 UTC, matsl commented
@rswgnu Just went through my notes and remembered I promised to change the names of the test cases and remove the "ebuts are one"-type of text to something else. So I will update the PR with that. But do review the other aspects if you have time.

2023-10-21 23:14 UTC, rswgnu commented
Let’s cover all of this when we talk tomorrow.-- BobOn Oct 21, 2023, at 11:33 PM, Mats Lidell ***@***.***> wrote:﻿
@rswgnu Just went through my notes and remembered I promised to change the names of the test cases and remove the "ebuts are one"-type of text to something else. So I will update the PR with that. But do review the other aspects if you have time.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-10-22 10:46 UTC, rswgnu requested changes

2023-10-22 10:46 UTC, rswgnu commented on hbdata.el
> +(defun hbdata--is-but-data-stored-in-buffer (key-src)
No, stick with colons until we do global renames in the future.  Place under a private function header as we normally do.

2023-10-22 10:46 UTC, rswgnu commented on hbdata.el
> +  (progn
progn not needed in function body.

2023-10-22 10:46 UTC, rswgnu commented on hbdata.el
> -    ;; Drafts of mail messages now have a buffer-file-name since they
Are you still handling the case highlighted in this comment?  Should be noted somewhere.

2023-10-22 12:49 UTC, matsl commented on hbdata.el
> -    ;; Drafts of mail messages now have a buffer-file-name since they
This part is moved into `hbdata:is-but-data-stored-in-buffer` that checks if we should look for button data in the current buffer or in `key-src.`

2023-10-22 14:48 UTC, rswgnu approved these changes

2023-10-22 15:16 UTC, merged

2023-10-30 06:45 UTC, rswgnu commented
I'd prefer not to merge my updates with hour hbdata changes until we have
resolved that these changes did not cause that recent issue you were going
to look at.  For now, I'll just deploy them to the rsw branch so you can
merge them and test them along with your other changes.  Let me know after
you are done testing the hbdata updates; my updates are all on the rsw
branch now.

On Sun, Oct 22, 2023 at 11:17 AM Mats Lidell ***@***.***>
wrote:

> Merged #394 <https://github.com/rswgnu/hyperbole/pull/394> into master.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/rswgnu/hyperbole/pull/394#event-10733481555>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE5WPD2VA7FAI6EC76JRKZDYAU2GVAVCNFSM6AAAAAA535UX5WVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJQG4ZTGNBYGE2TKNI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-10-30 20:58 UTC, matsl commented
@rswgnu  Oh, I'm sorry. Not sure if I saw some ghosts. I tried to go back to see if the error was in older versions which it was not. I then went back to latest master and could not recreate it there either!? The bug is just gone. :shrug: So I guess it was bad testing on my part. Maybe left the running Emacs in a bad state with moving back and forth between branches. 

All in all - I do currently not think there is any bug with the global button file. So I will not be adding any hbdata updates. All changes are in the master branch and looks good.  (The update was just a refactoring that should not affect anything else but the list of global buttons in the global button file.)

Do you still want me to test the changes in the rsw branch before you merge?

2023-10-30 21:47 UTC, rswgnu commented
If you have removed those updates, I can do the merge.  I’ll take a look.  Thanks.-- BobOn Oct 30, 2023, at 4:59 PM, Mats Lidell ***@***.***> wrote:﻿
@rswgnu  Oh, I'm sorry. Not sure if I saw some ghosts. I tried to go back to see if the error was in older versions which it was not. I then went back to latest master and could not recreate it there either!? The bug is just gone. 🤷 So I guess it was bad testing on my part. Maybe left the running Emacs in a bad state with moving back and forth between branches.
All in all - I do currently not think there is any bug with the global button file. So I will not be adding any hbdata updates. All changes are in the master branch and looks good.  (The update was just a refactoring that should not affect anything else but the list of global buttons in the global button file.)
Do you still want me to test the changes in the rsw branch before you merge?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-10-30 22:31 UTC, matsl commented
@rswgnu Oh, maybe you misunderstood me. This PR has been merged and is what I know a good change. The error I reported last week was after this change went in but I can't recreate that error now so I think the master branch is good with this change kept (since it fixes a bug). So what I was trying to say is that I will not be adding any **further** updates to `hbdata.el` so there is nothing new to be tested with you branch that is not already in master. Makes sense?

2023-10-30 23:22 UTC, rswgnu commented
Yes, makes sense.  So you feel lke you have sufficient test cases for hbdata/ebuts, e.g. added to mail at least 2 ebuts per message, same in a file or another type of buffer without a file, like scratch?-- BobOn Oct 30, 2023, at 6:31 PM, Mats Lidell ***@***.***> wrote:﻿
@rswgnu Oh, maybe you misunderstood me. This PR has been merged and is what I know a good change. The error I reported last week was after this change went in but I can't recreate that error now so I think the master branch is good with this change kept (since it fixes a bug). So what I was trying to say is that I will not be adding any further updates to hbdata.el so there is nothing new to be tested with you branch that is not already in master. Makes sense?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-10-31 09:11 UTC, matsl commented
> Yes, makes sense.  So you feel like you have sufficient test cases for hbdata/ebuts, e.g. added to mail at least 2 ebuts per message, same in a file or another type of buffer without a file, like scratch?

The change for fixing activating global buttons from mail-mode-like buffers is unrelated to adding local buttons to mail messages or to the scratch buffer. I do not think we have good coverage for the later cases so is something we can work on but I see that as another issue.

2023-10-31 12:43 UTC, rswgnu commented
Ok, as you see, I merged everything except the stefan patch into master.  Your ibut-link-directly test to dired has uncovered a bug when linking to a file, so I’ll work on that.  It would be good to have ibut-link-directly tests for multiple contexts in dired and then for various link-to types; once sttle on that, we could replicate for ebuts and gbuts.  This will be a very visible feature, so worthy of solid testing.Best regards,-- BobOn Oct 31, 2023, at 5:11 AM, Mats Lidell ***@***.***> wrote:﻿

Yes, makes sense.  So you feel like you have sufficient test cases for hbdata/ebuts, e.g. added to mail at least 2 ebuts per message, same in a file or another type of buffer without a file, like scratch?

The change for fixing activating global buttons from mail-mode-like buffers is unrelated to adding local buttons to mail messages or to the scratch buffer. I do not think we have good coverage for the later cases so is something we can work on but I see that as another issue.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>