Remove warnings
rswgnu/hyperbole pull request #409
Opened 2023-11-25 23:00 UTC by matsl

## What

Remove warnings

## Why

Recent updates have introduced a set of new warnings. This tries to remove the warnings by:
1. First of all using declare-function for declaring unknown functions. 
2. Fix call to derived-mode-p that only takes one arg, a list, and not multiple args.
3. Move private vars before their first use.
4. Remove a warning for a variable not used. (Not in a separate commit. See comment below.)

2023-11-25 23:01 UTC, matsl commented on hyrolo.el
> -			    match-start
match-start is not used and can thus be removed.

2023-11-26 09:00 UTC, rswgnu requested changes
derived-mode-p as of Emacs 28.2 uses &rest to create a single list from all args given, so sending it a list as an arg may break it and is not necessary.  Did the calling signature change at some point?

Remove that change and the rest looks good.

2023-11-26 13:37 UTC, rswgnu approved these changes

2023-11-26 15:20 UTC, matsl commented
Thanks for approving.

> derived-mode-p as of Emacs 28.2 uses &rest to create a single list from all args given, so sending it a list as an arg may break it and is not necessary. Did the calling signature change at some point?

It is changed in Emacs 30.1 to only take either one symbol or a list of symbols. So that hit me as a warning since I develop using the latest and greatest! 

But the test cases in CI made me aware that this change is not backwards compatible so I ha to revert that part of the PR, see commit https://github.com/rswgnu/hyperbole/pull/409/commits/1f4381d8e9ff4c8aaf2ed3ce207f5e64ea2cca8e. Hence point 2 is over struck although I understand it is not clear that the following comment is an explanation on why we keep the old code with using multiple symbols. The reason is that the change in 30.1 is backwards compatible so calling it with multiple symbols still work. I guess it will be removed at some point in the future. So for now we will have to live with the warning in Emacs 30.1. Maybe later it is time to deal with this.

2023-11-26 15:20 UTC, merged

2023-11-26 16:42 UTC, rswgnu commented
Yes, will be interesting to see why they made this change.-- BobOn Nov 26, 2023, at 3:20 PM, Mats Lidell ***@***.***> wrote:﻿
Thanks for approving.

derived-mode-p as of Emacs 28.2 uses &rest to create a single list from all args given, so sending it a list as an arg may break it and is not necessary. Did the calling signature change at some point?

It is changed in Emacs 30.1 to only take either one symbol or a list of symbols. So that hit me as a warning since I develop using the latest and greatest!
But the test cases in CI made me aware that this change is not backwards compatible so I ha to revert that part of the PR, see commit 1f4381d. Hence point 2 is over struck although I understand it is not clear that the following comment is an explanation on why we keep the old code with using multiple symbols. The reason is that the change in 30.1 is backwards compatible so calling it with multiple symbols still work. I guess it will be removed at some point in the future. So for now we will have to live with the warning in Emacs 30.1. Maybe later it is time to deal with this.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because your review was requested.Message ID: ***@***.***>

2023-11-26 21:29 UTC, matsl commented
> Yes, will be interesting to see why they made this change.

In the bug report there is some rational. https://lists.gnu.org/archive/html/bug-gnu-emacs/2023-11/msg00497.html