Require hbut so defib is defined, needed for compiling
rswgnu/hyperbole pull request #430
Opened 2024-01-03 14:53 UTC by matsl

# What

Require hbut so defib is defined, needed for compiling.

# Why

Without hbut the macro defib is not defined and the compile errors.

# Note

Fllymake can as well be required since it is a standard part of Emacs since 2003 and fixed a double spacing issue while at it.

2024-01-03 19:48 UTC, rswgnu requested changes

2024-01-03 19:48 UTC, rswgnu commented on hsys-flymake.el
> +(require 'flymake)
Read the above code comment for why we don’t want to require flymake.  If symbols are needed, just declare them.

2024-01-04 09:30 UTC, matsl commented on hsys-flymake.el
> +(require 'flymake)
:rofl: Sorry. Was a late night change to make the thing compile and when I was at it I throw in the require to remove warnings. This should work as expected now.

PS. Not particular happy about this type of design but might be the best or only way. Let's come back to this later. Don't want to derail and take time on this now. I'm happy with the solution for now and I need to think about possible alternatives. DS. :pray:

2024-01-04 10:37 UTC, rswgnu approved these changes

2024-01-04 10:38 UTC, rswgnu commented
Approved.On Jan 4, 2024, at 9:31 AM, Mats Lidell ***@***.***> wrote:﻿
@matsl requested your review on: #430 Require hbut so defib is defined, needed for compiling.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because your review was requested.Message ID: ***@***.***>

2024-01-04 12:49 UTC, merged