Remove ad hoc flycheck warnings
rswgnu/hyperbole pull request #468
Opened 2024-02-18 12:06 UTC by matsl

# What

Remove ad hoc flycheck warnings.

# Why

Just started the day with doing some cleanup of various flycheck warnings ranging from adding or fixing comments, removing white spaces...

2024-02-18 14:20 UTC, rswgnu requested changes
Just two grammar issues.

2024-02-18 14:20 UTC, rswgnu commented on hypb.el
> +  "Decode an URL-FILE-NAME."
a instead of an

2024-02-18 14:20 UTC, rswgnu commented on hsys-org.el
> +  "Return all org libraries that needs to be reloaded to avoid mixed versions."
need instead of needs

2024-02-18 22:56 UTC, matsl commented
@rswgnu Fixed review comments in [6a39b75](https://github.com/rswgnu/hyperbole/pull/468/commits/6a39b756eae5457c9b161f5031eebb9a6eca4c4c) and rebased. PTAL

2024-02-19 02:05 UTC, rswgnu approved these changes

2024-02-19 15:54 UTC, merged