Add tests for verifying action key on hyrolo matches
rswgnu/hyperbole pull request #486
Opened 2024-03-13 23:31 UTC by matsl

# What

Add tests for verifying action key on hyrolo matches

# Why

I noticed a problem with kotl files if the first line contains a slash
'/'.  So added a few tests to explore that problem. The problematic
test is marked as expected failure.

2024-03-14 01:37 UTC, rswgnu requested changes

2024-03-14 01:37 UTC, rswgnu commented on test/hyrolo-tests.el
> +  "Verify that moving to a match reaches the target buffer."
Need to change the doc string to match the test for each of the fun tions you added to this buffer.

2024-03-14 01:37 UTC, rswgnu commented on test/hyrolo-tests.el
> +          (hyrolo-grep "h/kotl")
/  is the child separator in hyrolo searches, so this means find the ‘h’ node and then a child node starting with ‘kotl’.  Should be documented in the manual.  So the test needs rewriting.  Maybe we should not have the same behavior in hyrolo-fgrep and hyrolo-grep.

2024-03-14 23:45 UTC, matsl commented on test/hyrolo-tests.el
> +  "Verify that moving to a match reaches the target buffer."
I will fix. I wanted to you too see it so I hacked and pushed away! ;-)

2024-03-15 00:05 UTC, matsl commented on test/hyrolo-tests.el
> +          (hyrolo-grep "h/kotl")
Ah I see. OK. To bad the point I was trying to make got lost because it got masked by that feature. So you are right that the test case needs to be rewritten but not because of the child separator. It is a problem with having a / in the first line in the cell if there is a match on that line. To late this night to rewrite it so I will redesign it tomorrow to better prove the point. Or I can show you a real life example on Sunday.

2024-03-15 22:37 UTC, matsl commented
@rswgnu Updated docstrings and reworked the tests slightly. Most important. Removed the slash in the search since that has special meaning i hyrolo but kept it in the contents of the cells. There are test cases both for slash in the first line in the cell and in the second line in the cell. There is different behavior.

2024-03-21 15:48 UTC, rswgnu approved these changes

2024-03-21 16:06 UTC, merged