Tests for org-links outside of org-mode
rswgnu/hyperbole pull request #512
Opened 2024-04-08 14:40 UTC by matsl

# What

Tests for org-links outside of org-mode.

# Why

There was a bug here where `hsys-org-enable-smart-keys' would
interfere with the org-links which is should not. It is only
applicable within `org-mode'. A fix for that has already been pushed.

2024-04-08 17:56 UTC, rswgnu requested changes
Look at the values of hsys-org-enable-smart-keys, need to test those to ensure nothing gets written that is conditionalized on that and stops these links from working.

2024-04-08 20:48 UTC, matsl commented
> Look at the values of hsys-org-enable-smart-keys, need to test those to ensure nothing gets written that is conditionalized on that and stops these links from working.

Are you saying that we need to run the test with all four values (unset buttons t nil)?

2024-04-08 22:12 UTC, rswgnu commented
Yes.-- BobOn Apr 8, 2024, at 4:49 PM, Mats Lidell ***@***.***> wrote:﻿

Look at the values of hsys-org-enable-smart-keys, need to test those to ensure nothing gets written that is conditionalized on that and stops these links from working.

Are you saying that we need to run the test with all four values (unset buttons t nil)?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because your review was requested.Message ID: ***@***.***>

2024-04-08 22:45 UTC, matsl commented
> Yes.

Easy to fix. Update tomorrow.

2024-04-09 07:55 UTC, matsl commented
> Easy to fix. Update tomorrow.

Looping over the possible values, repeating the test. PTAL.

2024-04-09 12:10 UTC, rswgnu requested changes
How are you trsting that the action key actually opens the link properly if that is the function you are mocking?

you are not trying to test that the variable is set right but to see if setting it affects recognition and execution of the button, i.e. runs the right action.

2024-04-09 21:22 UTC, matsl commented
> How are you trsting that the action key actually opens the link properly if that is the function you are mocking?
> 
> you are not trying to test that the variable is set right but to see if setting it affects recognition and execution of the button, i.e. runs the right action.

These are unit test that verifies `org-open-at-point-global` is called as a result of using the action-key (which it was not before your fix.) If the mocked function is not called the test fails. It does not attempt to verify that `org-open-at-point-global` does the right thing since that is an org function.

2024-04-10 00:06 UTC, rswgnu approved these changes

2024-04-10 00:07 UTC, rswgnu commented
Approved.

2024-04-10 03:39 UTC, merged