Add file exist check in ripgrep-msg and a test case
rswgnu/hyperbole pull request #564
Opened 2024-07-30 22:14 UTC by matsl

# What

Add a check if file in ripgrep output exists before concluding it is a
valid ripgrep-msg.

# Why

A number on a line can get interpreted as ripgrep line number which it
is not. That will block other buts from having their go at it. By
adding a check that the matching "file" exists makes it some what more
robust although I think there can still be problematic cases.

# Note

The error was found by having a iso date, like 2024-07-30, first on a
line. The string on the line above was interpreted as a file name. The
resulting action was a no-op but the action that should have been
triggered was not given its chance.

A test case triggering the bug for an unmodified ripgrep-msg is
supplied.

What do you think of requiring that the file listed in the ripgrep
output exists for it to be a valid button?

2024-07-30 23:48 UTC, rswgnu commented
Let’s discuss the pros and cons on a call and see where we land.  I would rather more narrowly exclude lines as needed, but am open to discussion.

2024-07-31 06:37 UTC, matsl commented
> I would rather more narrowly exclude lines as needed, but am open to discussion.

You need to elaborate so I understand what you are thinking of here. Lets talk on Sunday.

2024-08-23 18:15 UTC, rswgnu requested changes

2024-08-23 18:15 UTC, rswgnu commented on hibtypes.el
>                        (and (setq file (buffer-substring-no-properties (line-beginning-position) (line-end-position)))
Use this instead:

                      (and (setq file (string-trim (buffer-substring-no-properties (line-beginning-position) (match-beginning 0))))
                           (or (string-empty-p file)
			       (not (file-exists-p file)))))

2024-08-24 01:05 UTC, rswgnu approved these changes

2024-08-24 06:33 UTC, merged