Add tree-sitter "programming modes" supported by Hyperbole
rswgnu/hyperbole pull request #576
Opened 2024-08-16 22:03 UTC by matsl

# What

Add tree-sitter based modes for the programming modes currently
supported by Hyperbole.

# Why

Hyperbole uses buffers current major mode for checking if some
functionality shall be available in the buffer. With tree-sitter comes
modes for many programming languages and those can be used instead of
the old programming modes. These new modes are not recognized by
Hyperbole and if they are used the programming language specific
buttons are not recognized.

# Note

*Was looking into tree-sitter and to use the c++-ts-mode in a c++
file only to realize that Hyperbole smart-c++ was not available in
that case because we don't understand what c++-ts-mode is.*

This just blindly adds the tree-sitter modes to the program language
checks. There are no automatic tests that this works for all cases. On
the other hand we have no tests that it works for all the old modes
either.

It seems some old modes and tree sitter modes use the same base
mode. It could be possible to use that in Hyperbole to check for the
base mode instead to limit the modes to check for. This is not a
general pattern though so can only be applied after checking for each
programming language.

No analysis have been done if there are tree-sitter features that
Hyperbole utilized. This PR only allows the programming language to
derived by looking at the tree-sitter modes.

2024-08-17 22:09 UTC, rswgnu requested changes
Fix the comments and then it will be good.  -- rsw

2024-08-17 22:09 UTC, rswgnu commented on hui-mouse.el
> +    ((and (memq major-mode '(js2-mode js-mode js3-mode javascript-mode html-mode web-mode js-ts-mode))
Keep these mode names in alphabetical order.

2024-08-17 22:09 UTC, rswgnu commented on hui-select.el
> +             c++-ts-mode c-ts-mode java-ts-mode)
Same comment as above.  Check the whole PR for this ordering issue.

2024-08-18 07:48 UTC, matsl commented on hui-select.el
> +             c++-ts-mode c-ts-mode java-ts-mode)
> Same comment as above. Check the whole PR for this ordering issue.

The mode lists should now be sorted.

2024-08-18 17:18 UTC, rswgnu approved these changes

2024-08-18 17:40 UTC, merged