add more hywiki tests
rswgnu/hyperbole pull request #600
Opened 2024-11-02 17:28 UTC by matsl

# What

- Add hywiki-word-is-p test
- Use plain star wildcard and add a test
- Add test case for verifying property is updated on edit

# Why

Tests are good.

2024-11-02 17:34 UTC, matsl commented on hywiki.el
> +  (dired (concat hywiki-directory "*"
@rswgnu  Character classes are not supported by other shells than bash.

2024-11-02 17:38 UTC, rswgnu commented on hywiki.el
> +  (dired (concat hywiki-directory "*"
Bummer.  Will have to use English chars then, * is insufficient here.

2024-11-02 17:50 UTC, matsl commented on hywiki.el
> +  (dired (concat hywiki-directory "*"
Why? Will it not list all possible files plus files not being WikiWord files?

2024-11-02 17:52 UTC, rswgnu requested changes

2024-11-02 17:52 UTC, rswgnu commented on test/hywiki-tests.el
> +          (should-not (hproperty:but-get (point) 'face hywiki-word-face))
Have to have done some redisplay before this line, I think.

2024-11-02 18:21 UTC, matsl commented on test/hywiki-tests.el
> +          (should-not (hproperty:but-get (point) 'face hywiki-word-face))
An alternative would be to more directly test the code that does the highlighting to stay away from depending on redisplay. But that seems not be that straight forward.

2024-11-02 20:14 UTC, rswgnu commented on hywiki.el
> +  (dired (concat hywiki-directory "*"
Just HyWiki pages, as the doc indicates.

2024-11-02 20:25 UTC, rswgnu commented on test/hywiki-tests.el
> +          (should-not (hproperty:but-get (point) 'face hywiki-word-face))
You have to get the hooks set by HyWiki to run before you check the results but since your test is running during the command, this doesn't happen.  I think we make a function that invokes the appropriate hooks and then just use that before the should and should-not calls.

2024-11-02 22:01 UTC, matsl commented on hywiki.el
> +  (dired (concat hywiki-directory "*"
> Just HyWiki pages, as the doc indicates.
Maybe I misunderstand. I'm saying that using the shell pattern '*' will match all files in the hywiki-directory. So more than HyWiki-pages but is portable. Users will not likely have other files in that directory so is a small price to pay for supporting different shells.

2024-11-02 22:05 UTC, matsl commented on test/hywiki-tests.el
> +          (should-not (hproperty:but-get (point) 'face hywiki-word-face))
That is an alternative and seems to work fine.

2024-11-02 22:41 UTC, matsl commented on test/hywiki-tests.el
> +          (should-not (hproperty:but-get (point) 'face hywiki-word-face))
Added calls to `hywiki-maybe-highlight-page-names` before checking the face plus added a test case for deleting the first char in the WikiWord. That test case oddly works but running it manually does not.

So maybe I need to add calls to all hook functions as you suggest so behavior is consistent with interactive use.

2024-11-10 22:09 UTC, matsl commented on hywiki.el
> +  (dired (concat hywiki-directory "*"
I have removed this test case and will update it when the modified version gets merged.

2024-11-10 22:20 UTC, matsl commented
@rswgnu This seems to run more inline with what I see when I run it manually in interactive mode. All tests succeed except the one with removing the leading capital character. I also had to mark some of the test cases as only valid when interactive as well. PTAL.

2024-11-11 01:43 UTC, rswgnu approved these changes

2024-11-11 05:58 UTC, merged