remove warnings
rswgnu/hyperbole pull request #605
Opened 2024-11-12 19:46 UTC by matsl

# What

- Remove unused warning, comment out all occurences of new-buf-flag
- Add defvar and declare-function to silence warnings

# Why

We should minimize the number of warnings.

# Note

I'm keeping the new-buf-flag but commenting it put everywhere to be in
company with the comment later in the code. I would opt for removing
all of these comments.

2024-11-12 20:04 UTC, matsl commented on hyrolo.el
> +  (let (;;(new-buf-flag)
I propose we remove this altogether with the comment on line 2002. But the suggested change is a middle ground if the comment should stay.

2024-11-13 00:48 UTC, rswgnu requested changes

2024-11-13 00:48 UTC, rswgnu commented on hui-treemacs.el
> +(declare-function treemacs-add-and-display-current-project-exclusively "ext:treemacs")
Alphabetize these declarations.

2024-11-13 00:48 UTC, rswgnu commented on hywiki.el
> +(defvar action-key-modeline-buffer-id-function)  ;; "hui-mouse"
Alphabetize.

2024-11-13 00:48 UTC, rswgnu commented on hyrolo.el
> +  (let (;;(new-buf-flag)
So you are saying it is not used anywhere?  If so, just remove it.  If there are no other references to it anywhere in the code and the return value of its so setq is not used then it is just a leftover from some prior version and you should remove it.

2024-11-14 02:22 UTC, rswgnu approved these changes

2024-11-14 02:23 UTC, merged