Refactor tests to use with-simulated-input
rswgnu/hyperbole pull request #634
Opened 2024-12-28 15:24 UTC by matsl

# What

Use `with-simulated-input` in more tests.

# Why

Covers issues with using user input for constructing the referent
info.

# Note

Not all tests related to `hywiki-get-referent` has been refactored due
to rather big test setups and coverage in other tests.

2024-12-29 15:01 UTC, rswgnu requested changes

2024-12-29 23:25 UTC, matsl commented on test/hywiki-tests.el
> +	  (should (equal '(info-index . "(emacs)Top") (hywiki-get-referent "WikiWord"))))
Need to have some assistance here. Changed to "(emacs)files" but I guess that is still a node? Tried to use the function `(hywiki-find-referent "WikiRefNew" t)` interactively but I can't make it work. So I likely need some education here or there are problems with the functionality.

I was also expecting to find the possibility to add a referent in the hyperbole menu but had to call the function directly as given above to get the chance to select what type of referent it should be.

2024-12-29 23:31 UTC, rswgnu commented
In an Info manual, go to the end of the manual toc and you’ll see the indexes there.  Navigate to one and then choose any index entry name from there as your test case.Use {C-u C-h h h c} to be prompted for the referent type when using the Create command.-- BobOn Dec 29, 2024, at 6:25 PM, Mats Lidell ***@***.***> wrote:﻿
@matsl commented on this pull request.



In test/hywiki-tests.el:
>  	  (hywiki-add-info-index "WikiWord")
-	  (should (equal '(info-index . "(info)index-name") (hywiki-get-referent "WikiWord"))))
+	  (should (equal '(info-index . "(emacs)Top") (hywiki-get-referent "WikiWord"))))

Need to have some assistance here. Changed to "(emacs)files" but I guess that is still a node? Tried to use the function (hywiki-find-referent "WikiRefNew" t) interactively but I can't make it work. So I likely need some education here or there are problems with the functionality.
I was also expecting to find the possibility to add a referent in the hyperbole menu but had to call the function directly as given above to get the chance to select what type of referent it should be.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because your review was requested.Message ID: ***@***.***>

2024-12-29 23:50 UTC, matsl commented
> In an Info manual, go to the end of the manual toc and you’ll see the indexes there.  Navigate to one and then choose any index entry name from there as your test case, e.g. "(hyperbole)hyperbole-directory". 

"(emacs)files" is a valid index then. (But see my skepticism below)

> Use {C-u C-h h h c} to be prompted for the referent type when using the Create command.

Thanks for this. Although the docstring said use a prefix arg I did not expect that to be used with the regular hyperbole menu. But I have only been using it since 1993 so I guess I have a few more years to go before I can master it! ;-)

Anyway. It does not work for me. I'll send you a video to show what happens. (But that has to wait until tomorrow!)

2025-01-04 16:45 UTC, rswgnu approved these changes

2025-01-04 22:27 UTC, merged