Verify creation of pages and movement to pages
rswgnu/hyperbole pull request #635
Opened 2024-12-28 23:44 UTC by matsl

# What

Added or modified basic tests for creating pages and moving to pages
with sections.  Misc new tests and refactoring of old tests.  Update
hywiki to use sections.

# Why

Moving to pages and section in pages is basic HyWiki functionality so
we need to cover that in our tests.

# Note

Hywiki was missing using the sections with hpath:find. Added that in
order to write the test cases. Feel free to modify.

2024-12-29 15:28 UTC, rswgnu commented on hywiki.el
> +      (funcall hywiki-display-page-function (concat file section))
On this fix, you'll have to wait for me to push my update to this function and then drop yours, as it is more comprehensive.

2024-12-29 15:28 UTC, rswgnu commented on test/hywiki-tests.el
> +         (sections '("* Header" "** SubHeader" "*** SubSubHeader")))
I would add a single line body within each header section, to ensure the tests work in such cases.

2024-12-29 15:28 UTC, rswgnu commented on test/hywiki-tests.el
> +          (dolist (v '("WikiWord#"))
An Action Key press on a WikiWord with just a trailing # should probably either go to the first Org doc section or trigger an error.  What do you prefer?

2024-12-29 16:57 UTC, matsl commented on hywiki.el
> +      (funcall hywiki-display-page-function (concat file section))
> On this fix, you'll have to wait for me to push my update to this function and then drop yours, as it is more comprehensive.

That is OK and expected. Do your update and I'll remove this change. It is mostly there to allow me to work on these tests.

2024-12-29 17:01 UTC, matsl commented on test/hywiki-tests.el
> +          (dolist (v '("WikiWord#"))
> An Action Key press on a WikiWord with just a trailing # should probably either go to the first Org doc section or trigger an error. What do you prefer?

I think it currently raises an error. _(Hyperbole Action Key): No action defined for this context; try another location_ That is OK. Maybe just handle it as WikiWord would cause less questions from a user but will think about it.

2024-12-29 19:40 UTC, rswgnu commented on hywiki.el
> +      (funcall hywiki-display-page-function (concat file section))
Fix has  been pushed to master.

2024-12-29 22:41 UTC, matsl commented on test/hywiki-tests.el
> +          (dolist (v '("WikiWord#"))
Thinking more on this I think `WikiWord#` should be treated just like `WikiWord#non-existing-section`. 

Currently we just move to the WikiWord-page if the section does not exists, There is an error message that the section can't be found.  With an _empty_ section we should do something similar. We could even strip of the hash mark and treat it as a normal WikiWord.

2024-12-29 23:44 UTC, rswgnu commented on test/hywiki-tests.el
> +          (dolist (v '("WikiWord#"))
I think a wikiword that links to a page will display an existing buffer page with point wherever it was before the button was activated.  We need a way to say, display the beginning or first section of the page, so this is as good a way as any.

2025-01-04 20:30 UTC, rswgnu commented on test/hywiki-tests.el
> +          (dolist (v '("WikiWord#"))
I changed my thought on this.  With my next update, you'll be able to add :L1 at the end of a HyWikiWord referent to go to the first line of a wiki page, so if a # is given without a section name, it the HyWikiWord reference will just be ignored for now.

2025-01-04 22:19 UTC, matsl commented on test/hywiki-tests.el
> +          (dolist (v '("WikiWord#"))
OK. I will updated these tests when that change goes in.

2025-01-05 01:43 UTC, rswgnu requested changes

2025-01-05 01:43 UTC, rswgnu commented on test/hywiki-tests.el
> +(ert-deftest hywiki-tests--action-key-on-hy-wikiword-displays-page ()
No need for a dash, just use 'hywikiword' instead of 'hy-wikiword'.

2025-01-05 01:43 UTC, rswgnu commented on test/hywiki-tests.el
> +(ert-deftest hywiki-tests--assist-key-on-hy-wikiword-displays-help ()
Same as prior comment.

2025-01-05 01:43 UTC, rswgnu commented on test/hywiki-tests.el
> +          (dolist (v '("WikiWord#"))
That update has been made, so you can finish this PR.

2025-01-05 21:36 UTC, matsl commented
WikiWord# still errors. I got the impression that a single '#' would now be ignored so that WikiWord# still would link to the page?

2025-01-05 21:41 UTC, rswgnu commented
Proper behavior right now is that WikiWord# is not recognized nor
highlighted as a HyWikiWord.  Therefore, it is left for any other Action
Key action to process or the generic 'no action' error to occur.  That is
how you should test it right now.  It is too much effort to try to catch
that as a misformed HyWikiWord right now.  -- Bob

Message ID: ***@***.***>
>

2025-01-05 22:18 UTC, matsl commented
OK. The test is in line with that behavior so nothing needs to be updated.

2025-01-08 17:12 UTC, rswgnu approved these changes

2025-01-08 19:31 UTC, matsl commented
@rswgnu There is a regression on master. Moving to wikiword-sections and also line-column with wikiwords does not work. The test that verifies sections fails so this PR is not possible to merge. 

I have also verified manually on master that sections and line-column does not work so it is not necessarily a bad test.

2025-01-12 15:36 UTC, matsl commented
@rswgnu I added the test case with line and column numbers on WikiWords to this PR and marked that and the section (or suffix) test case as `expected failed.`  It was easiest in this case I think. You can merge this to master and work from there to fix the regressions since the error is already on master.

2025-01-19 05:36 UTC, merged