Use ibtypes tests for action key test
rswgnu/hyperbole pull request #67
Opened 2021-04-17 22:21 UTC by matsl

## What

- Used ibtypes test with action-key instead to check that proper ibtype is used.
- Moved hui tests to own file
- Some doc string updates

2021-04-17 22:43 UTC, rswgnu requested changes

2021-04-17 22:43 UTC, rswgnu commented on Changes
> +* test/hbut-tests.el (hub-mail-address-test, hub-pathname-test)
What does 'hub' stand for or mean?

Nice overall expansion in test coverage!

2021-04-17 22:43 UTC, rswgnu commented on test/demo-tests.el
> +Bug: Should work with action-key but does not.  Works with org modes hide function."
Add apostrophe: 'org mode's hide function'.

2021-04-17 22:43 UTC, rswgnu commented on test/hbut-tests.el
> +  (kill-buffer "hyperbole.el"))
Here, should check that buffer-file-name is non-nil to ensure it found the file and didn't just create a buffer with that name.

2021-04-17 22:43 UTC, rswgnu commented on test/hbut-tests.el
> +  (unwind-protect
Differentiate doc string from that of prior test.

2021-04-18 06:48 UTC, matsl commented on Changes
> +* test/hbut-tests.el (hub-mail-address-test, hub-pathname-test)
:-) Massive typo! Will change to `hbut`

2021-04-18 08:26 UTC, matsl commented on test/hbut-tests.el
> +  "Pathname with dash loads file."
This case fails after Emacs does native byte compilation, I think!? It then complain about "Invalid function: hact'". So changing this to reflect the proper behaviour and leave the byte compilation issue to elsewhere. Running "make clean && make bin && make test-all" seems like a good way to run the tests not to be affected by native compilation.

2021-04-18 08:31 UTC, matsl commented on test/hbut-tests.el
> +  "Pathname with dash loads file."
Oh, seems still to be a problem with make-all but `"make clean && make bin && make test` seems to be stable anyway.

Must experiment more with turning off the lazy native compilation maybe.

2021-04-18 14:02 UTC, rswgnu commented on test/hbut-tests.el
> +  "Pathname with dash loads file."
hact is a macro; if it is not loaded before compilation, it is assumed to be a function but then when executed is not defined as a function, hence the error.  So we have to find where it is used but not required and either require it or do so only when compiling.

2021-04-18 17:45 UTC, matsl commented on test/hbut-tests.el
> +  "Pathname with dash loads file."
As we said in IRL the test case works with not byte compiled hyperbole and with byte compiled hyperbole (after `make bin`). When Emacs asynchronously compiles the byte code to native code the test case fails with the given error message,

2021-04-18 20:42 UTC, rswgnu approved these changes

2021-04-18 20:42 UTC, rswgnu commented on test/hbut-tests.el
> +  "Pathname with dash loads file."
Okay, just log to a bug list and we'll close this for now.

2021-04-18 21:35 UTC, merged