Remove warning for unknown functions - part 1
rswgnu/hyperbole pull request #79
Opened 2021-05-09 22:00 UTC by matsl

## What

Remove warning for unknown functions - part 1

## Why

Warnings should be removed. The part 1 is because this is what I managed to do today.

2021-05-10 01:56 UTC, rswgnu requested changes
Consider this approved after the changes requested inline are made, so you can push.  -- Bob

2021-05-10 01:56 UTC, rswgnu commented on hargs.el
> +(declare-function monkey-filename "etx:monkey")
Typo: 'ext'.

2021-05-10 01:56 UTC, rswgnu commented on hmouse-drv.el
> +(declare-function br-to-view-window  "ext:oobr")
These should all be "ext:br" as they are in br.el of the OO-Browser.

2021-05-10 01:56 UTC, rswgnu commented on hmouse-tag.el
> +(declare-function br-edit "ext:oobr")
"ext:br"

2021-05-10 01:56 UTC, rswgnu commented on hmouse-tag.el
> +(declare-function br-edit-feature "ext:oobr")
"ext:br-ftr"

2021-05-10 01:56 UTC, rswgnu commented on hui-mouse.el
> +(require 'tar-mode)
(eval-when-compile (require 'tar-mode))

2021-05-10 01:56 UTC, rswgnu commented on hbdata.el
> +(require 'hgnus)
See if (require 'hmail) will work here instead, as it does not have all the dependencies of hgnus.el.  You are going to want (require 'hrmail) too at some point but that also has a lot of dependencies so I wouldn't add that right now but just declare the functions from there that you need.

2021-05-12 05:27 UTC, rswgnu commented on hbdata.el
> +(require 'hgnus)
Good question.  I would just leave them for now and lets get these added to the open Todo items and then I can look at it later.  Please merge if you feel ready.

2021-05-12 18:18 UTC, matsl commented on hbdata.el
> +(require 'hgnus)
I will merge and move on to part2 in a new PR! :-)

2021-05-12 18:18 UTC, merged