Silence a diverse set of warnings
rswgnu/hyperbole pull request #82
Opened 2021-05-12 21:31 UTC by matsl

## What

* Remove XEmacs functions
* Silence warning for filladapt-mode
* Use write-file-functions
* Surpress warnings for free vars

## Why

We need to silence more warnings :-)

2021-05-12 22:20 UTC, rswgnu requested changes

2021-05-12 22:20 UTC, rswgnu commented on hyrolo-menu.el
> -  (cond ((fboundp 'popup-mode-menu)
InfoDock is not the same as XEmacs.  Although it was built atop XEmacs, we may bring it back atop GNU Emacs at some point, so let's leave the InfoDock references and just remove the XEmacs ones, like zmacs-region-stays.  Any id- identifier is for InfoDock.

2021-05-13 08:05 UTC, matsl commented on hyrolo-menu.el
> -  (cond ((fboundp 'popup-mode-menu)
OK. I will change this. But would not InfoDock built on top of GNU Emacs use the menu functions in GNU Emacs!?

I know about the id-indentifiers and have not tried to address those yet but they do contribute to the warnings so at some point we would want do fix that as well.

2021-05-13 23:29 UTC, rswgnu approved these changes

2021-05-13 23:30 UTC, merged