Use compatibility macro for with-suppressed-warnings
rswgnu/hyperbole pull request #92
Opened 2021-05-17 19:55 UTC by matsl

## What

Use compatibility macro for with-suppressed-warnings

## Why

It was introduced in Emacs 27 and Elpa uses Emacs 26.  Alternative to #91 maybe?

2021-05-17 22:01 UTC, rswgnu requested changes

2021-05-17 22:01 UTC, rswgnu commented on kotl/kotl-mode.el
> +
This is the 2nd def of this macro in this commit.  I would change it to hypb:with-suppress-warnings and put it in the hypb.el file and then assure that that is required and you can utilize it wherever.

2021-05-18 06:05 UTC, matsl commented on kotl/kotl-mode.el
> +
Yes. This is WIP and wasn't sure where to put it since hyperbole.el does not require any other hypb-files. So wanted your wise suggestion. Will refactor this.

2021-05-18 21:39 UTC, matsl commented
I have refactored it. Don't know if it make sense for just to use in two places but could maybe be put to more use in the future.

2021-05-19 01:29 UTC, rswgnu approved these changes

2021-05-19 01:30 UTC, merged